# Train DeepAR For Selected Clusters

This notebook installs dependencies, loads the repo, and calls the reusable training script in `scripts/train_deepar_clusters.py`.

In [2]:
!pip uninstall -y torch torchvision torchaudio lightning pytorch-lightning gluonts sympy
!pip install -q sympy==1.13.1
!pip install -q torch==2.5.1 torchvision==0.20.1 torchaudio==2.5.1 --index-url https://download.pytorch.org/whl/cu121
!pip install -q gluonts pyarrow holidays lightning==2.5.0.post0

Found existing installation: torch 2.10.0+cu128
Uninstalling torch-2.10.0+cu128:
  Successfully uninstalled torch-2.10.0+cu128
Found existing installation: torchvision 0.25.0+cu128
Uninstalling torchvision-0.25.0+cu128:
  Successfully uninstalled torchvision-0.25.0+cu128
Found existing installation: torchaudio 2.10.0+cu128
Uninstalling torchaudio-2.10.0+cu128:
  Successfully uninstalled torchaudio-2.10.0+cu128
WARNING: Skipping lightning as it is not installed.
WARNING: Skipping pytorch-lightning as it is not installed.
WARNING: Skipping gluonts as it is not installed.
Found existing installation: sympy 1.14.0
Uninstalling sympy-1.14.0:
  Successfully uninstalled sympy-1.14.0
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.2/6.2 MB 119.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 780.4/780.4 MB 1.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.3/7.3 MB 29.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.4/3.4 MB 125.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 23.7/23.7 MB 113.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 823.6/823.6 kB 66.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.1/14.1 MB 143.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 664.8/664.8 MB 1.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 410.6/410.6 MB 3.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 121.6/121.6 MB 8.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.5/56.5 MB 43.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 124.2/124.2 MB 19.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 196.0/196.0 MB 5.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 188.7/188.7 MB 12.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 99.1/99.1 kB 11.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 209.6/209.6 MB 4.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 40.4/40.4 kB 4.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 815.2/815.2 kB 66.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.5/1.5 MB 93.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 65.5/65.5 kB 8.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 983.4/983.4 kB 75.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 857.3/857.3 kB 75.8 MB/s eta 0:00:00

In [3]:
import torch, torchvision, torchaudio, sympy
print("torch:", torch.__version__)
print("torchvision:", torchvision.__version__)
print("torchaudio:", torchaudio.__version__)
print("sympy:", sympy.__version__)
print("cuda:", torch.cuda.is_available())

torch: 2.5.1+cu121
torchvision: 0.20.1+cu121
torchaudio: 2.5.1+cu121
sympy: 1.13.1
cuda: True

In [26]:
import pandas as pd
import json
from train_deepar_clusters import TrainConfig, RandomSearchConfig, run_experiment, run_random_search
from gluonts.dataset.common import ListDataset
from train_deepar_clusters import (
    load_cluster_panels,
    build_metadata,
    build_dynamic_features,
    fit_predictor,
    set_seed,
)
from tqdm.auto import tqdm

In [4]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
%cd /content/drive/MyDrive/Electricity-Project

/content/drive/MyDrive/Electricity-Project

In [6]:
import torch
print('CUDA available:', torch.cuda.is_available())
if torch.cuda.is_available():
    print('GPU:', torch.cuda.get_device_name(0))

CUDA available: True
GPU: NVIDIA A100-SXM4-40GB

In [7]:
OUTPUT_DIR = None

HOLIDAY_COUNTRY = 'PT'

In [8]:
# Hyperparameters Tuning
RUN_RANDOM_SEARCH = True
N_TRIALS = 8
SEARCH_OUTPUT_DIR = None

SEARCH_SPACE = {
    'context_length_choices': (24 * 7, 24 * 14, 24 * 21),
    'hidden_size_choices': (48, 64, 96, 128),
    'dropout_rate_choices': (0.05, 0.1, 0.2, 0.3),
    'learning_rate_choices': (1e-3, 5e-4, 2e-4),
    'epochs_choices': (5, 10),
    'num_batches_per_epoch_choices': (50, 100),
    'batch_size_choices': (64,),
    'num_parallel_samples_choices': (50,),
}

# Cluster 2, 3

In [30]:
CLUSTER_IDS = (2, 3)

In [10]:
base_config = TrainConfig(
    train_path='train_hourly_preprocessed.parquet',
    test_path='test_hourly_preprocessed.parquet',
    cluster_path='clusters_3models.parquet',
    output_dir=OUTPUT_DIR,
    cluster_ids=CLUSTER_IDS,
    prediction_length=24,
    context_length=24 * 14,
    epochs=20,
    batch_size=64,
    num_batches_per_epoch=100,
    hidden_size=64,
    dropout_rate=0.1,
    use_hour_of_day=True,
    use_day_of_week=True,
    use_weekend=True,
    use_month=True,
    use_holiday=True,
    holiday_country=HOLIDAY_COUNTRY,
)

if RUN_RANDOM_SEARCH:
    search_config = RandomSearchConfig(
        n_trials=N_TRIALS,
        output_dir=SEARCH_OUTPUT_DIR,
        **SEARCH_SPACE,
    )
    results = run_random_search(base_config, search_config)
else:
    results = run_experiment(base_config)

results

[Trial 1/8] context=168, hidden=96, dropout=0.2, lr=0.001, epochs=10, batches=50

INFO: GPU available: True (cuda), used: True
INFO:lightning.pytorch.utilities.rank_zero:GPU available: True (cuda), used: True
INFO: TPU available: False, using: 0 TPU cores
INFO:lightning.pytorch.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO: HPU available: False, using: 0 HPUs
INFO:lightning.pytorch.utilities.rank_zero:HPU available: False, using: 0 HPUs
/usr/local/lib/python3.12/dist-packages/lightning/pytorch/trainer/configuration_validator.py:70: You defined a `validation_step` but have no `val_dataloader`. Skipping val loop.
INFO: You are using a CUDA device ('NVIDIA A100-SXM4-40GB') that has Tensor Cores. To properly utilize them, you should set `torch.set_float32_matmul_precision('medium' | 'high')` which will trade-off precision for performance. For more details, read https://pytorch.org/docs/stable/generated/torch.set_float32_matmul_precision.html#torch.set_float32_matmul_precision
INFO:lightning.pytorch.utilities.rank_zero:You are using a CUDA device ('NVIDIA A100-SXM4-40GB') that has Tensor Cores. To properly utilize them, you should set `torch.set_float32_matmul_precision('medium' | 'high')` which will trade-off precision for performance. For more details, read https://pytorch.org/docs/stable/generated/torch.set_float32_matmul_precision.html#torch.set_float32_matmul_precision
/usr/local/lib/python3.12/dist-packages/lightning/pytorch/callbacks/model_checkpoint.py:654: Checkpoint directory /content/drive/MyDrive/Electricity-Project/checkpoints exists and is not empty.
INFO: LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
INFO:lightning.pytorch.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
INFO:
  | Name  | Type        | Params | Mode  | In sizes                                                      | Out sizes
-----------------------------------------------------------------------------------------------------------------------------
0 | model | DeepARModel | 131 K  | train | [[1, 1], [1, 1], [1, 888, 6], [1, 888], [1, 888], [1, 24, 6]] | [1, 100, 24]
-----------------------------------------------------------------------------------------------------------------------------
131 K     Trainable params
0         Non-trainable params
131 K     Total params
0.525     Total estimated model params size (MB)
11        Modules in train mode
0         Modules in eval mode
INFO:lightning.pytorch.callbacks.model_summary:
  | Name  | Type        | Params | Mode  | In sizes                                                      | Out sizes
-----------------------------------------------------------------------------------------------------------------------------
0 | model | DeepARModel | 131 K  | train | [[1, 1], [1, 1], [1, 888, 6], [1, 888], [1, 888], [1, 24, 6]] | [1, 100, 24]
-----------------------------------------------------------------------------------------------------------------------------
131 K     Trainable params
0         Non-trainable params
131 K     Total params
0.525     Total estimated model params size (MB)
11        Modules in train mode
0         Modules in eval mode

Training: |          | 0/? [00:00<?, ?it/s]

INFO: Epoch 0, global step 50: 'train_loss' reached 7.15480 (best 7.15480), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=0-step=50.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 0, global step 50: 'train_loss' reached 7.15480 (best 7.15480), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=0-step=50.ckpt' as top 1
INFO: Epoch 1, global step 100: 'train_loss' reached 6.28267 (best 6.28267), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=1-step=100.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 1, global step 100: 'train_loss' reached 6.28267 (best 6.28267), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=1-step=100.ckpt' as top 1
INFO: Epoch 2, global step 150: 'train_loss' reached 6.07393 (best 6.07393), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=2-step=150.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 2, global step 150: 'train_loss' reached 6.07393 (best 6.07393), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=2-step=150.ckpt' as top 1
INFO: Epoch 3, global step 200: 'train_loss' reached 6.02680 (best 6.02680), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=3-step=200.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 3, global step 200: 'train_loss' reached 6.02680 (best 6.02680), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=3-step=200.ckpt' as top 1
INFO: Epoch 4, global step 250: 'train_loss' reached 5.93514 (best 5.93514), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=4-step=250-v3.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 4, global step 250: 'train_loss' reached 5.93514 (best 5.93514), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=4-step=250-v3.ckpt' as top 1
INFO: Epoch 5, global step 300: 'train_loss' reached 5.85714 (best 5.85714), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=5-step=300.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 5, global step 300: 'train_loss' reached 5.85714 (best 5.85714), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=5-step=300.ckpt' as top 1
INFO: Epoch 6, global step 350: 'train_loss' reached 5.83017 (best 5.83017), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=6-step=350.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 6, global step 350: 'train_loss' reached 5.83017 (best 5.83017), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=6-step=350.ckpt' as top 1
INFO: Epoch 7, global step 400: 'train_loss' reached 5.81376 (best 5.81376), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=7-step=400.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 7, global step 400: 'train_loss' reached 5.81376 (best 5.81376), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=7-step=400.ckpt' as top 1
INFO: Epoch 8, global step 450: 'train_loss' reached 5.77873 (best 5.77873), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=8-step=450-v2.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 8, global step 450: 'train_loss' reached 5.77873 (best 5.77873), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=8-step=450-v2.ckpt' as top 1
INFO: Epoch 9, global step 500: 'train_loss' reached 5.74838 (best 5.74838), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=9-step=500-v9.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 9, global step 500: 'train_loss' reached 5.74838 (best 5.74838), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=9-step=500-v9.ckpt' as top 1
INFO: `Trainer.fit` stopped: `max_epochs=10` reached.
INFO:lightning.pytorch.utilities.rank_zero:`Trainer.fit` stopped: `max_epochs=10` reached.

Validation rolling forecast:   0%|          | 0/17756 [00:00<?, ?window/s]

[Trial 2/8] context=168, hidden=48, dropout=0.1, lr=0.001, epochs=5, batches=100

INFO: GPU available: True (cuda), used: True
INFO:lightning.pytorch.utilities.rank_zero:GPU available: True (cuda), used: True
INFO: TPU available: False, using: 0 TPU cores
INFO:lightning.pytorch.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO: HPU available: False, using: 0 HPUs
INFO:lightning.pytorch.utilities.rank_zero:HPU available: False, using: 0 HPUs
/usr/local/lib/python3.12/dist-packages/lightning/pytorch/trainer/configuration_validator.py:70: You defined a `validation_step` but have no `val_dataloader`. Skipping val loop.
/usr/local/lib/python3.12/dist-packages/lightning/pytorch/callbacks/model_checkpoint.py:654: Checkpoint directory /content/drive/MyDrive/Electricity-Project/checkpoints exists and is not empty.
INFO: LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
INFO:lightning.pytorch.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
INFO:
  | Name  | Type        | Params | Mode  | In sizes                                                      | Out sizes
-----------------------------------------------------------------------------------------------------------------------------
0 | model | DeepARModel | 38.0 K | train | [[1, 1], [1, 1], [1, 888, 6], [1, 888], [1, 888], [1, 24, 6]] | [1, 100, 24]
-----------------------------------------------------------------------------------------------------------------------------
38.0 K    Trainable params
0         Non-trainable params
38.0 K    Total params
0.152     Total estimated model params size (MB)
11        Modules in train mode
0         Modules in eval mode
INFO:lightning.pytorch.callbacks.model_summary:
  | Name  | Type        | Params | Mode  | In sizes                                                      | Out sizes
-----------------------------------------------------------------------------------------------------------------------------
0 | model | DeepARModel | 38.0 K | train | [[1, 1], [1, 1], [1, 888, 6], [1, 888], [1, 888], [1, 24, 6]] | [1, 100, 24]
-----------------------------------------------------------------------------------------------------------------------------
38.0 K    Trainable params
0         Non-trainable params
38.0 K    Total params
0.152     Total estimated model params size (MB)
11        Modules in train mode
0         Modules in eval mode

Training: |          | 0/? [00:00<?, ?it/s]

INFO: Epoch 0, global step 100: 'train_loss' reached 6.95911 (best 6.95911), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=0-step=100.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 0, global step 100: 'train_loss' reached 6.95911 (best 6.95911), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=0-step=100.ckpt' as top 1
INFO: Epoch 1, global step 200: 'train_loss' reached 6.14539 (best 6.14539), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=1-step=200.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 1, global step 200: 'train_loss' reached 6.14539 (best 6.14539), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=1-step=200.ckpt' as top 1
INFO: Epoch 2, global step 300: 'train_loss' reached 5.96207 (best 5.96207), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=2-step=300.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 2, global step 300: 'train_loss' reached 5.96207 (best 5.96207), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=2-step=300.ckpt' as top 1
INFO: Epoch 3, global step 400: 'train_loss' reached 5.82725 (best 5.82725), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=3-step=400-v2.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 3, global step 400: 'train_loss' reached 5.82725 (best 5.82725), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=3-step=400-v2.ckpt' as top 1
INFO: Epoch 4, global step 500: 'train_loss' reached 5.75929 (best 5.75929), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=4-step=500-v5.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 4, global step 500: 'train_loss' reached 5.75929 (best 5.75929), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=4-step=500-v5.ckpt' as top 1
INFO: `Trainer.fit` stopped: `max_epochs=5` reached.
INFO:lightning.pytorch.utilities.rank_zero:`Trainer.fit` stopped: `max_epochs=5` reached.

Validation rolling forecast:   0%|          | 0/17756 [00:00<?, ?window/s]

[Trial 3/8] context=336, hidden=128, dropout=0.1, lr=0.001, epochs=10, batches=100

INFO: GPU available: True (cuda), used: True
INFO:lightning.pytorch.utilities.rank_zero:GPU available: True (cuda), used: True
INFO: TPU available: False, using: 0 TPU cores
INFO:lightning.pytorch.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO: HPU available: False, using: 0 HPUs
INFO:lightning.pytorch.utilities.rank_zero:HPU available: False, using: 0 HPUs
/usr/local/lib/python3.12/dist-packages/lightning/pytorch/trainer/configuration_validator.py:70: You defined a `validation_step` but have no `val_dataloader`. Skipping val loop.
/usr/local/lib/python3.12/dist-packages/lightning/pytorch/callbacks/model_checkpoint.py:654: Checkpoint directory /content/drive/MyDrive/Electricity-Project/checkpoints exists and is not empty.
INFO: LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
INFO:lightning.pytorch.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
INFO:
  | Name  | Type        | Params | Mode  | In sizes                                                         | Out sizes
--------------------------------------------------------------------------------------------------------------------------------
0 | model | DeepARModel | 224 K  | train | [[1, 1], [1, 1], [1, 1056, 6], [1, 1056], [1, 1056], [1, 24, 6]] | [1, 100, 24]
--------------------------------------------------------------------------------------------------------------------------------
224 K     Trainable params
0         Non-trainable params
224 K     Total params
0.897     Total estimated model params size (MB)
11        Modules in train mode
0         Modules in eval mode
INFO:lightning.pytorch.callbacks.model_summary:
  | Name  | Type        | Params | Mode  | In sizes                                                         | Out sizes
--------------------------------------------------------------------------------------------------------------------------------
0 | model | DeepARModel | 224 K  | train | [[1, 1], [1, 1], [1, 1056, 6], [1, 1056], [1, 1056], [1, 24, 6]] | [1, 100, 24]
--------------------------------------------------------------------------------------------------------------------------------
224 K     Trainable params
0         Non-trainable params
224 K     Total params
0.897     Total estimated model params size (MB)
11        Modules in train mode
0         Modules in eval mode

Training: |          | 0/? [00:00<?, ?it/s]

INFO: Epoch 0, global step 100: 'train_loss' reached 6.61858 (best 6.61858), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=0-step=100.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 0, global step 100: 'train_loss' reached 6.61858 (best 6.61858), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=0-step=100.ckpt' as top 1
INFO: Epoch 1, global step 200: 'train_loss' reached 6.00694 (best 6.00694), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=1-step=200.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 1, global step 200: 'train_loss' reached 6.00694 (best 6.00694), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=1-step=200.ckpt' as top 1
INFO: Epoch 2, global step 300: 'train_loss' reached 5.86370 (best 5.86370), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=2-step=300.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 2, global step 300: 'train_loss' reached 5.86370 (best 5.86370), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=2-step=300.ckpt' as top 1
INFO: Epoch 3, global step 400: 'train_loss' reached 5.71819 (best 5.71819), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=3-step=400-v2.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 3, global step 400: 'train_loss' reached 5.71819 (best 5.71819), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=3-step=400-v2.ckpt' as top 1
INFO: Epoch 4, global step 500: 'train_loss' reached 5.63122 (best 5.63122), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=4-step=500-v6.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 4, global step 500: 'train_loss' reached 5.63122 (best 5.63122), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=4-step=500-v6.ckpt' as top 1
INFO: Epoch 5, global step 600: 'train_loss' reached 5.55216 (best 5.55216), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=5-step=600.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 5, global step 600: 'train_loss' reached 5.55216 (best 5.55216), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=5-step=600.ckpt' as top 1
INFO: Epoch 6, global step 700: 'train_loss' was not in top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 6, global step 700: 'train_loss' was not in top 1
INFO: Epoch 7, global step 800: 'train_loss' was not in top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 7, global step 800: 'train_loss' was not in top 1
INFO: Epoch 8, global step 900: 'train_loss' reached 5.52312 (best 5.52312), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=8-step=900-v2.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 8, global step 900: 'train_loss' reached 5.52312 (best 5.52312), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=8-step=900-v2.ckpt' as top 1
INFO: Epoch 9, global step 1000: 'train_loss' reached 5.51478 (best 5.51478), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=9-step=1000-v1.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 9, global step 1000: 'train_loss' reached 5.51478 (best 5.51478), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=9-step=1000-v1.ckpt' as top 1
INFO: `Trainer.fit` stopped: `max_epochs=10` reached.
INFO:lightning.pytorch.utilities.rank_zero:`Trainer.fit` stopped: `max_epochs=10` reached.

Validation rolling forecast:   0%|          | 0/17756 [00:00<?, ?window/s]

[Trial 4/8] context=504, hidden=128, dropout=0.05, lr=0.0005, epochs=5, batches=50

INFO: GPU available: True (cuda), used: True
INFO:lightning.pytorch.utilities.rank_zero:GPU available: True (cuda), used: True
INFO: TPU available: False, using: 0 TPU cores
INFO:lightning.pytorch.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO: HPU available: False, using: 0 HPUs
INFO:lightning.pytorch.utilities.rank_zero:HPU available: False, using: 0 HPUs
/usr/local/lib/python3.12/dist-packages/lightning/pytorch/trainer/configuration_validator.py:70: You defined a `validation_step` but have no `val_dataloader`. Skipping val loop.
/usr/local/lib/python3.12/dist-packages/lightning/pytorch/callbacks/model_checkpoint.py:654: Checkpoint directory /content/drive/MyDrive/Electricity-Project/checkpoints exists and is not empty.
INFO: LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
INFO:lightning.pytorch.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
INFO:
  | Name  | Type        | Params | Mode  | In sizes                                                         | Out sizes
--------------------------------------------------------------------------------------------------------------------------------
0 | model | DeepARModel | 224 K  | train | [[1, 1], [1, 1], [1, 1224, 6], [1, 1224], [1, 1224], [1, 24, 6]] | [1, 100, 24]
--------------------------------------------------------------------------------------------------------------------------------
224 K     Trainable params
0         Non-trainable params
224 K     Total params
0.897     Total estimated model params size (MB)
11        Modules in train mode
0         Modules in eval mode
INFO:lightning.pytorch.callbacks.model_summary:
  | Name  | Type        | Params | Mode  | In sizes                                                         | Out sizes
--------------------------------------------------------------------------------------------------------------------------------
0 | model | DeepARModel | 224 K  | train | [[1, 1], [1, 1], [1, 1224, 6], [1, 1224], [1, 1224], [1, 24, 6]] | [1, 100, 24]
--------------------------------------------------------------------------------------------------------------------------------
224 K     Trainable params
0         Non-trainable params
224 K     Total params
0.897     Total estimated model params size (MB)
11        Modules in train mode
0         Modules in eval mode

Training: |          | 0/? [00:00<?, ?it/s]

INFO: Epoch 0, global step 50: 'train_loss' reached 7.15484 (best 7.15484), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=0-step=50.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 0, global step 50: 'train_loss' reached 7.15484 (best 7.15484), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=0-step=50.ckpt' as top 1
INFO: Epoch 1, global step 100: 'train_loss' reached 6.21873 (best 6.21873), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=1-step=100.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 1, global step 100: 'train_loss' reached 6.21873 (best 6.21873), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=1-step=100.ckpt' as top 1
INFO: Epoch 2, global step 150: 'train_loss' reached 6.03629 (best 6.03629), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=2-step=150.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 2, global step 150: 'train_loss' reached 6.03629 (best 6.03629), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=2-step=150.ckpt' as top 1
INFO: Epoch 3, global step 200: 'train_loss' reached 5.95479 (best 5.95479), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=3-step=200.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 3, global step 200: 'train_loss' reached 5.95479 (best 5.95479), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=3-step=200.ckpt' as top 1
INFO: Epoch 4, global step 250: 'train_loss' reached 5.88995 (best 5.88995), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=4-step=250-v3.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 4, global step 250: 'train_loss' reached 5.88995 (best 5.88995), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=4-step=250-v3.ckpt' as top 1
INFO: `Trainer.fit` stopped: `max_epochs=5` reached.
INFO:lightning.pytorch.utilities.rank_zero:`Trainer.fit` stopped: `max_epochs=5` reached.

Validation rolling forecast:   0%|          | 0/17756 [00:00<?, ?window/s]

[Trial 5/8] context=168, hidden=128, dropout=0.3, lr=0.001, epochs=5, batches=100

INFO: GPU available: True (cuda), used: True
INFO:lightning.pytorch.utilities.rank_zero:GPU available: True (cuda), used: True
INFO: TPU available: False, using: 0 TPU cores
INFO:lightning.pytorch.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO: HPU available: False, using: 0 HPUs
INFO:lightning.pytorch.utilities.rank_zero:HPU available: False, using: 0 HPUs
/usr/local/lib/python3.12/dist-packages/lightning/pytorch/trainer/configuration_validator.py:70: You defined a `validation_step` but have no `val_dataloader`. Skipping val loop.
/usr/local/lib/python3.12/dist-packages/lightning/pytorch/callbacks/model_checkpoint.py:654: Checkpoint directory /content/drive/MyDrive/Electricity-Project/checkpoints exists and is not empty.
INFO: LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
INFO:lightning.pytorch.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
INFO:
  | Name  | Type        | Params | Mode  | In sizes                                                      | Out sizes
-----------------------------------------------------------------------------------------------------------------------------
0 | model | DeepARModel | 224 K  | train | [[1, 1], [1, 1], [1, 888, 6], [1, 888], [1, 888], [1, 24, 6]] | [1, 100, 24]
-----------------------------------------------------------------------------------------------------------------------------
224 K     Trainable params
0         Non-trainable params
224 K     Total params
0.897     Total estimated model params size (MB)
11        Modules in train mode
0         Modules in eval mode
INFO:lightning.pytorch.callbacks.model_summary:
  | Name  | Type        | Params | Mode  | In sizes                                                      | Out sizes
-----------------------------------------------------------------------------------------------------------------------------
0 | model | DeepARModel | 224 K  | train | [[1, 1], [1, 1], [1, 888, 6], [1, 888], [1, 888], [1, 24, 6]] | [1, 100, 24]
-----------------------------------------------------------------------------------------------------------------------------
224 K     Trainable params
0         Non-trainable params
224 K     Total params
0.897     Total estimated model params size (MB)
11        Modules in train mode
0         Modules in eval mode

Training: |          | 0/? [00:00<?, ?it/s]

INFO: Epoch 0, global step 100: 'train_loss' reached 6.68048 (best 6.68048), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=0-step=100.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 0, global step 100: 'train_loss' reached 6.68048 (best 6.68048), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=0-step=100.ckpt' as top 1
INFO: Epoch 1, global step 200: 'train_loss' reached 6.02561 (best 6.02561), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=1-step=200.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 1, global step 200: 'train_loss' reached 6.02561 (best 6.02561), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=1-step=200.ckpt' as top 1
INFO: Epoch 2, global step 300: 'train_loss' reached 5.94975 (best 5.94975), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=2-step=300.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 2, global step 300: 'train_loss' reached 5.94975 (best 5.94975), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=2-step=300.ckpt' as top 1
INFO: Epoch 3, global step 400: 'train_loss' reached 5.86916 (best 5.86916), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=3-step=400-v2.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 3, global step 400: 'train_loss' reached 5.86916 (best 5.86916), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=3-step=400-v2.ckpt' as top 1
INFO: Epoch 4, global step 500: 'train_loss' reached 5.75015 (best 5.75015), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=4-step=500-v6.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 4, global step 500: 'train_loss' reached 5.75015 (best 5.75015), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=4-step=500-v6.ckpt' as top 1
INFO: `Trainer.fit` stopped: `max_epochs=5` reached.
INFO:lightning.pytorch.utilities.rank_zero:`Trainer.fit` stopped: `max_epochs=5` reached.

Validation rolling forecast:   0%|          | 0/17756 [00:00<?, ?window/s]

[Trial 6/8] context=168, hidden=96, dropout=0.1, lr=0.0002, epochs=10, batches=50

INFO: GPU available: True (cuda), used: True
INFO:lightning.pytorch.utilities.rank_zero:GPU available: True (cuda), used: True
INFO: TPU available: False, using: 0 TPU cores
INFO:lightning.pytorch.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO: HPU available: False, using: 0 HPUs
INFO:lightning.pytorch.utilities.rank_zero:HPU available: False, using: 0 HPUs
/usr/local/lib/python3.12/dist-packages/lightning/pytorch/trainer/configuration_validator.py:70: You defined a `validation_step` but have no `val_dataloader`. Skipping val loop.
/usr/local/lib/python3.12/dist-packages/lightning/pytorch/callbacks/model_checkpoint.py:654: Checkpoint directory /content/drive/MyDrive/Electricity-Project/checkpoints exists and is not empty.
INFO: LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
INFO:lightning.pytorch.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
INFO:
  | Name  | Type        | Params | Mode  | In sizes                                                      | Out sizes
-----------------------------------------------------------------------------------------------------------------------------
0 | model | DeepARModel | 131 K  | train | [[1, 1], [1, 1], [1, 888, 6], [1, 888], [1, 888], [1, 24, 6]] | [1, 100, 24]
-----------------------------------------------------------------------------------------------------------------------------
131 K     Trainable params
0         Non-trainable params
131 K     Total params
0.525     Total estimated model params size (MB)
11        Modules in train mode
0         Modules in eval mode
INFO:lightning.pytorch.callbacks.model_summary:
  | Name  | Type        | Params | Mode  | In sizes                                                      | Out sizes
-----------------------------------------------------------------------------------------------------------------------------
0 | model | DeepARModel | 131 K  | train | [[1, 1], [1, 1], [1, 888, 6], [1, 888], [1, 888], [1, 24, 6]] | [1, 100, 24]
-----------------------------------------------------------------------------------------------------------------------------
131 K     Trainable params
0         Non-trainable params
131 K     Total params
0.525     Total estimated model params size (MB)
11        Modules in train mode
0         Modules in eval mode

Training: |          | 0/? [00:00<?, ?it/s]

INFO: Epoch 0, global step 50: 'train_loss' reached 7.75689 (best 7.75689), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=0-step=50.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 0, global step 50: 'train_loss' reached 7.75689 (best 7.75689), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=0-step=50.ckpt' as top 1
INFO: Epoch 1, global step 100: 'train_loss' reached 6.76194 (best 6.76194), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=1-step=100.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 1, global step 100: 'train_loss' reached 6.76194 (best 6.76194), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=1-step=100.ckpt' as top 1
INFO: Epoch 2, global step 150: 'train_loss' reached 6.30237 (best 6.30237), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=2-step=150.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 2, global step 150: 'train_loss' reached 6.30237 (best 6.30237), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=2-step=150.ckpt' as top 1
INFO: Epoch 3, global step 200: 'train_loss' reached 6.15193 (best 6.15193), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=3-step=200.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 3, global step 200: 'train_loss' reached 6.15193 (best 6.15193), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=3-step=200.ckpt' as top 1
INFO: Epoch 4, global step 250: 'train_loss' reached 6.00051 (best 6.00051), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=4-step=250-v4.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 4, global step 250: 'train_loss' reached 6.00051 (best 6.00051), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=4-step=250-v4.ckpt' as top 1
INFO: Epoch 5, global step 300: 'train_loss' reached 5.98989 (best 5.98989), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=5-step=300.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 5, global step 300: 'train_loss' reached 5.98989 (best 5.98989), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=5-step=300.ckpt' as top 1
INFO: Epoch 6, global step 350: 'train_loss' reached 5.93805 (best 5.93805), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=6-step=350.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 6, global step 350: 'train_loss' reached 5.93805 (best 5.93805), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=6-step=350.ckpt' as top 1
INFO: Epoch 7, global step 400: 'train_loss' reached 5.91529 (best 5.91529), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=7-step=400.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 7, global step 400: 'train_loss' reached 5.91529 (best 5.91529), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=7-step=400.ckpt' as top 1
INFO: Epoch 8, global step 450: 'train_loss' reached 5.89549 (best 5.89549), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=8-step=450-v2.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 8, global step 450: 'train_loss' reached 5.89549 (best 5.89549), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=8-step=450-v2.ckpt' as top 1
INFO: Epoch 9, global step 500: 'train_loss' reached 5.85251 (best 5.85251), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=9-step=500-v10.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 9, global step 500: 'train_loss' reached 5.85251 (best 5.85251), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=9-step=500-v10.ckpt' as top 1
INFO: `Trainer.fit` stopped: `max_epochs=10` reached.
INFO:lightning.pytorch.utilities.rank_zero:`Trainer.fit` stopped: `max_epochs=10` reached.

Validation rolling forecast:   0%|          | 0/17756 [00:00<?, ?window/s]

[Trial 7/8] context=504, hidden=128, dropout=0.05, lr=0.0005, epochs=10, batches=50

INFO: GPU available: True (cuda), used: True
INFO:lightning.pytorch.utilities.rank_zero:GPU available: True (cuda), used: True
INFO: TPU available: False, using: 0 TPU cores
INFO:lightning.pytorch.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO: HPU available: False, using: 0 HPUs
INFO:lightning.pytorch.utilities.rank_zero:HPU available: False, using: 0 HPUs
/usr/local/lib/python3.12/dist-packages/lightning/pytorch/trainer/configuration_validator.py:70: You defined a `validation_step` but have no `val_dataloader`. Skipping val loop.
/usr/local/lib/python3.12/dist-packages/lightning/pytorch/callbacks/model_checkpoint.py:654: Checkpoint directory /content/drive/MyDrive/Electricity-Project/checkpoints exists and is not empty.
INFO: LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
INFO:lightning.pytorch.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
INFO:
  | Name  | Type        | Params | Mode  | In sizes                                                         | Out sizes
--------------------------------------------------------------------------------------------------------------------------------
0 | model | DeepARModel | 224 K  | train | [[1, 1], [1, 1], [1, 1224, 6], [1, 1224], [1, 1224], [1, 24, 6]] | [1, 100, 24]
--------------------------------------------------------------------------------------------------------------------------------
224 K     Trainable params
0         Non-trainable params
224 K     Total params
0.897     Total estimated model params size (MB)
11        Modules in train mode
0         Modules in eval mode
INFO:lightning.pytorch.callbacks.model_summary:
  | Name  | Type        | Params | Mode  | In sizes                                                         | Out sizes
--------------------------------------------------------------------------------------------------------------------------------
0 | model | DeepARModel | 224 K  | train | [[1, 1], [1, 1], [1, 1224, 6], [1, 1224], [1, 1224], [1, 24, 6]] | [1, 100, 24]
--------------------------------------------------------------------------------------------------------------------------------
224 K     Trainable params
0         Non-trainable params
224 K     Total params
0.897     Total estimated model params size (MB)
11        Modules in train mode
0         Modules in eval mode

Training: |          | 0/? [00:00<?, ?it/s]

INFO: Epoch 0, global step 50: 'train_loss' reached 7.21031 (best 7.21031), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=0-step=50.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 0, global step 50: 'train_loss' reached 7.21031 (best 7.21031), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=0-step=50.ckpt' as top 1
INFO: Epoch 1, global step 100: 'train_loss' reached 6.26371 (best 6.26371), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=1-step=100.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 1, global step 100: 'train_loss' reached 6.26371 (best 6.26371), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=1-step=100.ckpt' as top 1
INFO: Epoch 2, global step 150: 'train_loss' reached 6.07821 (best 6.07821), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=2-step=150.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 2, global step 150: 'train_loss' reached 6.07821 (best 6.07821), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=2-step=150.ckpt' as top 1
INFO: Epoch 3, global step 200: 'train_loss' reached 5.95529 (best 5.95529), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=3-step=200.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 3, global step 200: 'train_loss' reached 5.95529 (best 5.95529), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=3-step=200.ckpt' as top 1
INFO: Epoch 4, global step 250: 'train_loss' reached 5.92456 (best 5.92456), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=4-step=250-v4.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 4, global step 250: 'train_loss' reached 5.92456 (best 5.92456), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=4-step=250-v4.ckpt' as top 1
INFO: Epoch 5, global step 300: 'train_loss' reached 5.86336 (best 5.86336), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=5-step=300.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 5, global step 300: 'train_loss' reached 5.86336 (best 5.86336), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=5-step=300.ckpt' as top 1
INFO: Epoch 6, global step 350: 'train_loss' reached 5.82991 (best 5.82991), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=6-step=350.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 6, global step 350: 'train_loss' reached 5.82991 (best 5.82991), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=6-step=350.ckpt' as top 1
INFO: Epoch 7, global step 400: 'train_loss' was not in top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 7, global step 400: 'train_loss' was not in top 1
INFO: Epoch 8, global step 450: 'train_loss' was not in top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 8, global step 450: 'train_loss' was not in top 1
INFO: Epoch 9, global step 500: 'train_loss' reached 5.80096 (best 5.80096), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=9-step=500-v11.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 9, global step 500: 'train_loss' reached 5.80096 (best 5.80096), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=9-step=500-v11.ckpt' as top 1
INFO: `Trainer.fit` stopped: `max_epochs=10` reached.
INFO:lightning.pytorch.utilities.rank_zero:`Trainer.fit` stopped: `max_epochs=10` reached.

Validation rolling forecast:   0%|          | 0/17756 [00:00<?, ?window/s]

[Trial 8/8] context=168, hidden=48, dropout=0.05, lr=0.0005, epochs=5, batches=100

INFO: GPU available: True (cuda), used: True
INFO:lightning.pytorch.utilities.rank_zero:GPU available: True (cuda), used: True
INFO: TPU available: False, using: 0 TPU cores
INFO:lightning.pytorch.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO: HPU available: False, using: 0 HPUs
INFO:lightning.pytorch.utilities.rank_zero:HPU available: False, using: 0 HPUs
/usr/local/lib/python3.12/dist-packages/lightning/pytorch/trainer/configuration_validator.py:70: You defined a `validation_step` but have no `val_dataloader`. Skipping val loop.
/usr/local/lib/python3.12/dist-packages/lightning/pytorch/callbacks/model_checkpoint.py:654: Checkpoint directory /content/drive/MyDrive/Electricity-Project/checkpoints exists and is not empty.
INFO: LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
INFO:lightning.pytorch.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
INFO:
  | Name  | Type        | Params | Mode  | In sizes                                                      | Out sizes
-----------------------------------------------------------------------------------------------------------------------------
0 | model | DeepARModel | 38.0 K | train | [[1, 1], [1, 1], [1, 888, 6], [1, 888], [1, 888], [1, 24, 6]] | [1, 100, 24]
-----------------------------------------------------------------------------------------------------------------------------
38.0 K    Trainable params
0         Non-trainable params
38.0 K    Total params
0.152     Total estimated model params size (MB)
11        Modules in train mode
0         Modules in eval mode
INFO:lightning.pytorch.callbacks.model_summary:
  | Name  | Type        | Params | Mode  | In sizes                                                      | Out sizes
-----------------------------------------------------------------------------------------------------------------------------
0 | model | DeepARModel | 38.0 K | train | [[1, 1], [1, 1], [1, 888, 6], [1, 888], [1, 888], [1, 24, 6]] | [1, 100, 24]
-----------------------------------------------------------------------------------------------------------------------------
38.0 K    Trainable params
0         Non-trainable params
38.0 K    Total params
0.152     Total estimated model params size (MB)
11        Modules in train mode
0         Modules in eval mode

Training: |          | 0/? [00:00<?, ?it/s]

INFO: Epoch 0, global step 100: 'train_loss' reached 7.20432 (best 7.20432), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=0-step=100.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 0, global step 100: 'train_loss' reached 7.20432 (best 7.20432), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=0-step=100.ckpt' as top 1
INFO: Epoch 1, global step 200: 'train_loss' reached 6.18444 (best 6.18444), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=1-step=200.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 1, global step 200: 'train_loss' reached 6.18444 (best 6.18444), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=1-step=200.ckpt' as top 1
INFO: Epoch 2, global step 300: 'train_loss' reached 5.91778 (best 5.91778), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=2-step=300.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 2, global step 300: 'train_loss' reached 5.91778 (best 5.91778), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=2-step=300.ckpt' as top 1
INFO: Epoch 3, global step 400: 'train_loss' reached 5.84073 (best 5.84073), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=3-step=400-v2.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 3, global step 400: 'train_loss' reached 5.84073 (best 5.84073), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=3-step=400-v2.ckpt' as top 1
INFO: Epoch 4, global step 500: 'train_loss' reached 5.80873 (best 5.80873), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=4-step=500-v7.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 4, global step 500: 'train_loss' reached 5.80873 (best 5.80873), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=4-step=500-v7.ckpt' as top 1
INFO: `Trainer.fit` stopped: `max_epochs=5` reached.
INFO:lightning.pytorch.utilities.rank_zero:`Trainer.fit` stopped: `max_epochs=5` reached.

Validation rolling forecast:   0%|          | 0/17756 [00:00<?, ?window/s]

{'summary_df':    trial  overall_mape  overall_wmape  overall_epsilon_mape  context_length  \
 0      7      7.263247       6.213088              7.683969             504
 1      3      7.158662       6.307977              7.553069             336
 2      2      8.394817       6.747770              8.808058             168
 3      8      7.998184       6.939348              8.409334             168
 4      5      7.888569       7.156149              8.270409             168
 5      4      9.166676       7.286303              9.598702             504
 6      1      8.319133       7.609014              8.699319             168
 7      6      8.822342       7.855966              9.219142             168

    hidden_size  dropout_rate  learning_rate  epochs  num_batches_per_epoch  \
 0          128          0.05         0.0005      10                     50
 1          128          0.10         0.0010      10                    100
 2           48          0.10         0.0010       5                    100
 3           48          0.05         0.0005       5                    100
 4          128          0.30         0.0010       5                    100
 5          128          0.05         0.0005       5                     50
 6           96          0.20         0.0010      10                     50
 7           96          0.10         0.0002      10                     50

    batch_size  num_parallel_samples  \
 0          64                    50
 1          64                    50
 2          64                    50
 3          64                    50
 4          64                    50
 5          64                    50
 6          64                    50
 7          64                    50

                                      prediction_path  cluster_2_mape  \
 0  outputs/deepar_random_search_2_3/trial_07/deep...        6.118415
 1  outputs/deepar_random_search_2_3/trial_03/deep...        6.193130
 2  outputs/deepar_random_search_2_3/trial_02/deep...        7.215106
 3  outputs/deepar_random_search_2_3/trial_08/deep...        6.937115
 4  outputs/deepar_random_search_2_3/trial_05/deep...        7.140871
 5  outputs/deepar_random_search_2_3/trial_04/deep...        7.830813
 6  outputs/deepar_random_search_2_3/trial_01/deep...        7.502144
 7  outputs/deepar_random_search_2_3/trial_06/deep...        7.891813

    cluster_3_mape  cluster_2_wmape  cluster_3_wmape  cluster_2_epsilon_mape  \
 0       13.246160         5.684308         8.486128                6.403359
 1       12.204550         5.814528         8.429145                6.463395
 2       14.560013         6.273687         8.785689                7.500079
 3       13.543353         6.505316         8.805100                7.233807
 4       11.796054         6.937071         8.097890                7.406096
 5       16.147926         6.674568         9.915937                8.121289
 6       12.588732         7.222671         9.269771                7.774998
 7       13.685301         7.427053         9.699714                8.174057

    cluster_3_epsilon_mape
 0               14.376193
 1               13.247492
 2               15.643301
 3               14.552414
 4               12.787138
 5               17.319379
 6               13.529642
 7               14.680549  ,
 'summary_path': 'outputs/deepar_random_search_2_3/random_search_summary.csv',
 'results_path': 'outputs/deepar_random_search_2_3/random_search_results.json',
 'best_result': {'config': {'train_path': 'train_hourly_preprocessed.parquet',
   'test_path': 'test_hourly_preprocessed.parquet',
   'cluster_path': 'clusters_3models.parquet',
   'output_dir': 'outputs/deepar_random_search_2_3/trial_01',
   'cluster_ids': (2, 3),
   'cluster_col': 'cluster_kmeans',
   'freq': 'h',
   'prediction_length': 24,
   'context_length': 168,
   'epochs': 10,
   'learning_rate': 0.001,
   'batch_size': 64,
   'num_batches_per_epoch': 50,
   'num_layers': 2,
   'hidden_size': 96,
   'dropout_rate': 0.2,
   'num_parallel_samples': 50,
   'seed': 42,
   'use_hour_of_day': True,
   'use_day_of_week': True,
   'use_weekend': True,
   'use_month': True,
   'use_holiday': True,
   'holiday_country': 'PT',
   'validation_months': 3},
  'metrics': {'overall_mape': 8.319132545044846,
   'overall_wmape': 7.609014271471214,
   'overall_epsilon_mape': 8.699319280305774,
   'cluster_mape': {'2': 7.5021440397126335, '3': 12.588731542996575},
   'cluster_wmape': {'2': 7.222670591725606, '3': 9.269770982438862},
   'cluster_epsilon_mape': {'2': 7.77499834637219, '3': 13.529641580216762},
   'n_predictions': 426144,
   'n_nonzero_targets': 426140,
   'n_meters': 193,
   'meter_mape_head': {'MT_098': 8.398973179812451,
    'MT_099': 11.098590932350238,
    'MT_100': 11.975368654396753,
    'MT_101': 8.946056604484586,
    'MT_103': 7.651470179019992,
    'MT_104': 10.618071122269829,
    'MT_105': 11.185523869494167,
    'MT_125': 10.157327339131838,
    'MT_126': 7.360810335417385,
    'MT_135': 13.558324060729406}},
  'dynamic_feature_names': ['hour_of_day',
   'day_of_week',
   'weekend',
   'month',
   'holiday'],
  'prediction_path': 'outputs/deepar_random_search_2_3/trial_01/deepar_clusters_2_3_validation_predictions.parquet',
  'metadata_path': 'outputs/deepar_random_search_2_3/trial_01/deepar_clusters_2_3_validation_metadata.parquet',
  'evaluation_split': 'validation',
  'train_range': ['2012-10-01 00:00:00', '2014-06-30 23:00:00'],
  'validation_range': ['2014-07-01 00:00:00', '2014-09-30 23:00:00'],
  'test_range': ['2014-10-01 00:00:00', '2014-12-31 23:00:00']}}

In [11]:
summary_path = "outputs/deepar_random_search_2_3/random_search_summary.csv"
results_path = "outputs/deepar_random_search_2_3/random_search_results.json"

summary_df = pd.read_csv(summary_path)
summary_df.head()

,trial,overall_mape,overall_wmape,overall_epsilon_mape,context_length,hidden_size,dropout_rate,learning_rate,epochs,num_batches_per_epoch,batch_size,num_parallel_samples,prediction_path,cluster_2_mape,cluster_3_mape,cluster_2_wmape,cluster_3_wmape,cluster_2_epsilon_mape,cluster_3_epsilon_mape
0,7,7.263247,6.213088,7.683969,504,128,0.05,0.0005,10,50,64,50,outputs/deepar_random_search_2_3/trial_07/deep...,6.118415,13.246160,5.684308,8.486128,6.403359,14.376193
1,3,7.158662,6.307977,7.553069,336,128,0.10,0.0010,10,100,64,50,outputs/deepar_random_search_2_3/trial_03/deep...,6.193130,12.204550,5.814528,8.429145,6.463395,13.247492
2,2,8.394817,6.747770,8.808058,168,48,0.10,0.0010,5,100,64,50,outputs/deepar_random_search_2_3/trial_02/deep...,7.215106,14.560013,6.273687,8.785689,7.500079,15.643301
3,8,7.998184,6.939348,8.409334,168,48,0.05,0.0005,5,100,64,50,outputs/deepar_random_search_2_3/trial_08/deep...,6.937115,13.543353,6.505316,8.805100,7.233807,14.552414
4,5,7.888569,7.156149,8.270409,168,128,0.30,0.0010,5,100,64,50,outputs/deepar_random_search_2_3/trial_05/deep...,7.140871,11.796054,6.937071,8.097890,7.406096,12.787138

In [12]:
best_row = summary_df.iloc[0]
best_row

trial                                                                     7
overall_mape                                                       7.263247
overall_wmape                                                      6.213088
overall_epsilon_mape                                               7.683969
context_length                                                          504
hidden_size                                                             128
dropout_rate                                                           0.05
learning_rate                                                        0.0005
epochs                                                                   10
num_batches_per_epoch                                                    50
batch_size                                                               64
num_parallel_samples                                                     50
prediction_path           outputs/deepar_random_search_2_3/trial_07/deep...
cluster_2_mape                                                     6.118415
cluster_3_mape                                                     13.24616
cluster_2_wmape                                                    5.684308
cluster_3_wmape                                                    8.486128
cluster_2_epsilon_mape                                             6.403359
cluster_3_epsilon_mape                                            14.376193
Name: 0, dtype: object

In [13]:
best_cols = [
    "overall_wmape", "overall_mape",
    "context_length", "hidden_size", "dropout_rate", "learning_rate",
    "epochs", "num_batches_per_epoch", "batch_size", "num_parallel_samples"
]

extra_cols = [
    c for c in summary_df.columns
    if c.startswith("cluster_") and c.endswith(("wmape", "mape"))
]

summary_df.loc[[0], best_cols + extra_cols].T

                                 0
overall_wmape             6.213088
overall_mape              7.263247
context_length          504.000000
hidden_size             128.000000
dropout_rate              0.050000
learning_rate             0.000500
epochs                   10.000000
num_batches_per_epoch    50.000000
batch_size               64.000000
num_parallel_samples     50.000000
cluster_2_mape            6.118415
cluster_3_mape           13.246160
cluster_2_wmape           5.684308
cluster_3_wmape           8.486128
cluster_2_epsilon_mape    6.403359
cluster_3_epsilon_mape   14.376193

In [14]:
best_pred_path = best_row["prediction_path"]
best_pred_df = pd.read_parquet(best_pred_path)
best_pred_df.head()

,timestamp,meter_id,cluster_id,y_true,y_pred,forecast_start,ape,epsilon_ape
0,2014-07-01 00:00:00,MT_098,3,1219.110379,1367.979004,2014-07-01,12.211251,12.201242
1,2014-07-01 01:00:00,MT_098,3,784.184514,963.058228,2014-07-01,22.810156,22.781106
2,2014-07-01 02:00:00,MT_098,3,747.940692,880.813232,2014-07-01,17.765117,17.741397
3,2014-07-01 03:00:00,MT_098,3,777.594728,830.005798,2014-07-01,6.740152,6.731496
4,2014-07-01 04:00:00,MT_098,3,780.889621,751.439392,2014-07-01,3.771369,3.766546

In [31]:
best_config = TrainConfig(
    train_path="train_hourly_preprocessed.parquet",
    test_path="test_hourly_preprocessed.parquet",
    cluster_path="clusters_3models.parquet",
    cluster_ids=CLUSTER_IDS,
    output_dir=OUTPUT_DIR,
    freq="h",
    prediction_length=24,
    context_length=int(best_row["context_length"]),
    epochs=int(best_row["epochs"]),
    learning_rate=float(best_row["learning_rate"]),
    batch_size=int(best_row["batch_size"]),
    num_batches_per_epoch=int(best_row["num_batches_per_epoch"]),
    num_layers=2,
    hidden_size=int(best_row["hidden_size"]),
    dropout_rate=float(best_row["dropout_rate"]),
    num_parallel_samples=int(best_row["num_parallel_samples"]),
    seed=42,
    use_hour_of_day=True,
    use_day_of_week=True,
    use_weekend=True,
    use_month=True,
    use_holiday=True,
    holiday_country=HOLIDAY_COUNTRY,
)

In [32]:
set_seed(best_config.seed)

train_panel, test_panel, labels = load_cluster_panels(best_config)

history_panel = pd.concat([train_panel, test_panel]).sort_index()

meta = build_metadata(history_panel, labels, best_config)

future_start = history_panel.index.max() + pd.Timedelta(hours=1)
future_end = (future_start.to_period("M") + 2).end_time.floor("h")
future_index = pd.date_range(future_start, future_end, freq="h")

print("history:", history_panel.index.min(), "->", history_panel.index.max(), history_panel.shape)
print("future :", future_index.min(), "->", future_index.max(), len(future_index))

dynamic_feat_df = build_dynamic_features(history_panel.index, future_index, best_config)

predictor = fit_predictor(history_panel, meta, dynamic_feat_df.loc[history_panel.index.union(future_index)], best_config)

print("final predictor trained")

history: 2012-10-01 00:00:00 -> 2014-12-31 23:00:00 (19728, 193)
future : 2015-01-01 00:00:00 -> 2015-03-31 23:00:00 2160

INFO: GPU available: True (cuda), used: True
INFO:lightning.pytorch.utilities.rank_zero:GPU available: True (cuda), used: True
INFO: TPU available: False, using: 0 TPU cores
INFO:lightning.pytorch.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO: HPU available: False, using: 0 HPUs
INFO:lightning.pytorch.utilities.rank_zero:HPU available: False, using: 0 HPUs
/usr/local/lib/python3.12/dist-packages/lightning/pytorch/trainer/configuration_validator.py:70: You defined a `validation_step` but have no `val_dataloader`. Skipping val loop.
/usr/local/lib/python3.12/dist-packages/lightning/pytorch/callbacks/model_checkpoint.py:654: Checkpoint directory /content/drive/MyDrive/Electricity-Project/checkpoints exists and is not empty.
INFO: LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
INFO:lightning.pytorch.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
INFO:
  | Name  | Type        | Params | Mode  | In sizes                                                         | Out sizes
--------------------------------------------------------------------------------------------------------------------------------
0 | model | DeepARModel | 224 K  | train | [[1, 1], [1, 1], [1, 1224, 6], [1, 1224], [1, 1224], [1, 24, 6]] | [1, 100, 24]
--------------------------------------------------------------------------------------------------------------------------------
224 K     Trainable params
0         Non-trainable params
224 K     Total params
0.897     Total estimated model params size (MB)
11        Modules in train mode
0         Modules in eval mode
INFO:lightning.pytorch.callbacks.model_summary:
  | Name  | Type        | Params | Mode  | In sizes                                                         | Out sizes
--------------------------------------------------------------------------------------------------------------------------------
0 | model | DeepARModel | 224 K  | train | [[1, 1], [1, 1], [1, 1224, 6], [1, 1224], [1, 1224], [1, 24, 6]] | [1, 100, 24]
--------------------------------------------------------------------------------------------------------------------------------
224 K     Trainable params
0         Non-trainable params
224 K     Total params
0.897     Total estimated model params size (MB)
11        Modules in train mode
0         Modules in eval mode

Training: |          | 0/? [00:00<?, ?it/s]

INFO: Epoch 0, global step 50: 'train_loss' reached 7.23476 (best 7.23476), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=0-step=50.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 0, global step 50: 'train_loss' reached 7.23476 (best 7.23476), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=0-step=50.ckpt' as top 1
INFO: Epoch 1, global step 100: 'train_loss' reached 6.16488 (best 6.16488), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=1-step=100.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 1, global step 100: 'train_loss' reached 6.16488 (best 6.16488), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=1-step=100.ckpt' as top 1
INFO: Epoch 2, global step 150: 'train_loss' was not in top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 2, global step 150: 'train_loss' was not in top 1
INFO: Epoch 3, global step 200: 'train_loss' reached 5.90885 (best 5.90885), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=3-step=200.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 3, global step 200: 'train_loss' reached 5.90885 (best 5.90885), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=3-step=200.ckpt' as top 1
INFO: Epoch 4, global step 250: 'train_loss' reached 5.81613 (best 5.81613), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=4-step=250-v5.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 4, global step 250: 'train_loss' reached 5.81613 (best 5.81613), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=4-step=250-v5.ckpt' as top 1
INFO: Epoch 5, global step 300: 'train_loss' was not in top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 5, global step 300: 'train_loss' was not in top 1
INFO: Epoch 6, global step 350: 'train_loss' reached 5.72480 (best 5.72480), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=6-step=350.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 6, global step 350: 'train_loss' reached 5.72480 (best 5.72480), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=6-step=350.ckpt' as top 1
INFO: Epoch 7, global step 400: 'train_loss' was not in top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 7, global step 400: 'train_loss' was not in top 1
INFO: Epoch 8, global step 450: 'train_loss' was not in top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 8, global step 450: 'train_loss' was not in top 1
INFO: Epoch 9, global step 500: 'train_loss' reached 5.67195 (best 5.67195), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=9-step=500-v15.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 9, global step 500: 'train_loss' reached 5.67195 (best 5.67195), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=9-step=500-v15.ckpt' as top 1
INFO: `Trainer.fit` stopped: `max_epochs=10` reached.
INFO:lightning.pytorch.utilities.rank_zero:`Trainer.fit` stopped: `max_epochs=10` reached.

final predictor trained

In [33]:
future_pred_frames = []
step = best_config.prediction_length  # 24

total_windows = sum((len(future_index) + step - 1) // step for _ in history_panel.columns)
progress = tqdm(total=total_windows, desc="Future rolling forecast", unit="window")

for meter_id in history_panel.columns:
    history = history_panel[meter_id].astype(float).copy()

    static_cat = [int(meta.loc[meter_id, "cluster_code"])]
    static_real = [float(meta.loc[meter_id, "log_mean_hourly_load"])]
    cluster_id = int(meta.loc[meter_id, "cluster_id"])

    meter_future_frames = []

    for start_idx in range(0, len(future_index), step):
        end_idx = min(start_idx + step, len(future_index))
        horizon = end_idx - start_idx
        forecast_slice = future_index[start_idx:end_idx]

        record = {
            "item_id": str(meter_id),
            "start": history.index[0],
            "target": history.to_numpy(),
            "feat_static_cat": static_cat,
            "feat_static_real": static_real,
        }

        if not dynamic_feat_df.empty:
            dynamic_index = history.index.append(forecast_slice)
            record["feat_dynamic_real"] = dynamic_feat_df.loc[dynamic_index].to_numpy(dtype=float).T

        ds = ListDataset([record], freq=best_config.freq)
        forecast = next(predictor.predict(ds, num_samples=best_config.num_parallel_samples))

        pred_mean = np.asarray(forecast.mean[:horizon], dtype=float)

        meter_future_frames.append(
            pd.DataFrame(
                {
                    "timestamp": forecast_slice,
                    "meter_id": meter_id,
                    "cluster_id": cluster_id,
                    "y_pred": pred_mean,
                }
            )
        )

        history_extension = pd.Series(pred_mean, index=forecast_slice)
        history = pd.concat([history, history_extension])

        progress.update(1)

    future_pred_frames.append(pd.concat(meter_future_frames, ignore_index=True))

progress.close()

future_pred_df = pd.concat(future_pred_frames, ignore_index=True)
future_pred_df.head()

Future rolling forecast:   0%|          | 0/17370 [00:00<?, ?window/s]

            timestamp meter_id  cluster_id      y_pred
0 2015-01-01 00:00:00   MT_098           3  983.492920
1 2015-01-01 01:00:00   MT_098           3  753.809631
2 2015-01-01 02:00:00   MT_098           3  778.887573
3 2015-01-01 03:00:00   MT_098           3  748.515991
4 2015-01-01 04:00:00   MT_098           3  702.720642

In [34]:
cluster_future_df = (
    future_pred_df.groupby(["timestamp", "cluster_id"], as_index=False)["y_pred"]
    .sum()
    .sort_values(["cluster_id", "timestamp"])
)

cluster_future_df.head()

            timestamp  cluster_id         y_pred
0 2015-01-01 00:00:00           2  207886.626015
2 2015-01-01 01:00:00           2  192406.921200
4 2015-01-01 02:00:00           2  200499.144157
6 2015-01-01 03:00:00           2  205478.383068
8 2015-01-01 04:00:00           2  216566.189610

In [35]:
future_pred_path = "outputs/future_3months_predictions_2_3.parquet"
cluster_future_path = "outputs/future_3months_cluster_sum_2_3.parquet"

future_pred_df.to_parquet(future_pred_path, index=False)
cluster_future_df.to_parquet(cluster_future_path, index=False)

print("saved meter-level forecast to:", future_pred_path)
print("saved cluster-level forecast to:", cluster_future_path)

saved meter-level forecast to: outputs/future_3months_predictions_2_3.parquet
saved cluster-level forecast to: outputs/future_3months_cluster_sum_2_3.parquet

# Cluster 1, 11

In [15]:
CLUSTER_IDS = (1, 11)

In [16]:
base_config_2 = TrainConfig(
    train_path='train_hourly_preprocessed.parquet',
    test_path='test_hourly_preprocessed.parquet',
    cluster_path='clusters_3models.parquet',
    output_dir=OUTPUT_DIR,
    cluster_ids=CLUSTER_IDS,
    prediction_length=24,
    context_length=24 * 14,
    epochs=20,
    batch_size=64,
    num_batches_per_epoch=100,
    hidden_size=64,
    dropout_rate=0.1,
    use_hour_of_day=True,
    use_day_of_week=True,
    use_weekend=True,
    use_month=True,
    use_holiday=True,
    holiday_country=HOLIDAY_COUNTRY,
)

if RUN_RANDOM_SEARCH:
    search_config_2 = RandomSearchConfig(
        n_trials=N_TRIALS,
        output_dir=SEARCH_OUTPUT_DIR,
        **SEARCH_SPACE,
    )
    results_2 = run_random_search(base_config_2, search_config_2)
else:
    results_2 = run_experiment(base_config_2)

results_2

[Trial 1/8] context=168, hidden=96, dropout=0.2, lr=0.001, epochs=10, batches=50

INFO: GPU available: True (cuda), used: True
INFO:lightning.pytorch.utilities.rank_zero:GPU available: True (cuda), used: True
INFO: TPU available: False, using: 0 TPU cores
INFO:lightning.pytorch.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO: HPU available: False, using: 0 HPUs
INFO:lightning.pytorch.utilities.rank_zero:HPU available: False, using: 0 HPUs
/usr/local/lib/python3.12/dist-packages/lightning/pytorch/trainer/configuration_validator.py:70: You defined a `validation_step` but have no `val_dataloader`. Skipping val loop.
/usr/local/lib/python3.12/dist-packages/lightning/pytorch/callbacks/model_checkpoint.py:654: Checkpoint directory /content/drive/MyDrive/Electricity-Project/checkpoints exists and is not empty.
INFO: LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
INFO:lightning.pytorch.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
INFO:
  | Name  | Type        | Params | Mode  | In sizes                                                      | Out sizes
-----------------------------------------------------------------------------------------------------------------------------
0 | model | DeepARModel | 131 K  | train | [[1, 1], [1, 1], [1, 888, 6], [1, 888], [1, 888], [1, 24, 6]] | [1, 100, 24]
-----------------------------------------------------------------------------------------------------------------------------
131 K     Trainable params
0         Non-trainable params
131 K     Total params
0.525     Total estimated model params size (MB)
11        Modules in train mode
0         Modules in eval mode
INFO:lightning.pytorch.callbacks.model_summary:
  | Name  | Type        | Params | Mode  | In sizes                                                      | Out sizes
-----------------------------------------------------------------------------------------------------------------------------
0 | model | DeepARModel | 131 K  | train | [[1, 1], [1, 1], [1, 888, 6], [1, 888], [1, 888], [1, 24, 6]] | [1, 100, 24]
-----------------------------------------------------------------------------------------------------------------------------
131 K     Trainable params
0         Non-trainable params
131 K     Total params
0.525     Total estimated model params size (MB)
11        Modules in train mode
0         Modules in eval mode

Training: |          | 0/? [00:00<?, ?it/s]

INFO: Epoch 0, global step 50: 'train_loss' reached 5.81283 (best 5.81283), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=0-step=50.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 0, global step 50: 'train_loss' reached 5.81283 (best 5.81283), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=0-step=50.ckpt' as top 1
INFO: Epoch 1, global step 100: 'train_loss' reached 5.14165 (best 5.14165), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=1-step=100.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 1, global step 100: 'train_loss' reached 5.14165 (best 5.14165), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=1-step=100.ckpt' as top 1
INFO: Epoch 2, global step 150: 'train_loss' reached 4.96525 (best 4.96525), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=2-step=150.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 2, global step 150: 'train_loss' reached 4.96525 (best 4.96525), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=2-step=150.ckpt' as top 1
INFO: Epoch 3, global step 200: 'train_loss' reached 4.85365 (best 4.85365), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=3-step=200.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 3, global step 200: 'train_loss' reached 4.85365 (best 4.85365), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=3-step=200.ckpt' as top 1
INFO: Epoch 4, global step 250: 'train_loss' reached 4.84842 (best 4.84842), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=4-step=250-v4.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 4, global step 250: 'train_loss' reached 4.84842 (best 4.84842), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=4-step=250-v4.ckpt' as top 1
INFO: Epoch 5, global step 300: 'train_loss' reached 4.77828 (best 4.77828), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=5-step=300.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 5, global step 300: 'train_loss' reached 4.77828 (best 4.77828), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=5-step=300.ckpt' as top 1
INFO: Epoch 6, global step 350: 'train_loss' reached 4.66090 (best 4.66090), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=6-step=350.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 6, global step 350: 'train_loss' reached 4.66090 (best 4.66090), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=6-step=350.ckpt' as top 1
INFO: Epoch 7, global step 400: 'train_loss' was not in top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 7, global step 400: 'train_loss' was not in top 1
INFO: Epoch 8, global step 450: 'train_loss' was not in top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 8, global step 450: 'train_loss' was not in top 1
INFO: Epoch 9, global step 500: 'train_loss' reached 4.61203 (best 4.61203), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=9-step=500-v12.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 9, global step 500: 'train_loss' reached 4.61203 (best 4.61203), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=9-step=500-v12.ckpt' as top 1
INFO: `Trainer.fit` stopped: `max_epochs=10` reached.
INFO:lightning.pytorch.utilities.rank_zero:`Trainer.fit` stopped: `max_epochs=10` reached.

Validation rolling forecast:   0%|          | 0/7360 [00:00<?, ?window/s]

[Trial 2/8] context=168, hidden=48, dropout=0.1, lr=0.001, epochs=5, batches=100

INFO: GPU available: True (cuda), used: True
INFO:lightning.pytorch.utilities.rank_zero:GPU available: True (cuda), used: True
INFO: TPU available: False, using: 0 TPU cores
INFO:lightning.pytorch.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO: HPU available: False, using: 0 HPUs
INFO:lightning.pytorch.utilities.rank_zero:HPU available: False, using: 0 HPUs
/usr/local/lib/python3.12/dist-packages/lightning/pytorch/trainer/configuration_validator.py:70: You defined a `validation_step` but have no `val_dataloader`. Skipping val loop.
/usr/local/lib/python3.12/dist-packages/lightning/pytorch/callbacks/model_checkpoint.py:654: Checkpoint directory /content/drive/MyDrive/Electricity-Project/checkpoints exists and is not empty.
INFO: LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
INFO:lightning.pytorch.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
INFO:
  | Name  | Type        | Params | Mode  | In sizes                                                      | Out sizes
-----------------------------------------------------------------------------------------------------------------------------
0 | model | DeepARModel | 38.0 K | train | [[1, 1], [1, 1], [1, 888, 6], [1, 888], [1, 888], [1, 24, 6]] | [1, 100, 24]
-----------------------------------------------------------------------------------------------------------------------------
38.0 K    Trainable params
0         Non-trainable params
38.0 K    Total params
0.152     Total estimated model params size (MB)
11        Modules in train mode
0         Modules in eval mode
INFO:lightning.pytorch.callbacks.model_summary:
  | Name  | Type        | Params | Mode  | In sizes                                                      | Out sizes
-----------------------------------------------------------------------------------------------------------------------------
0 | model | DeepARModel | 38.0 K | train | [[1, 1], [1, 1], [1, 888, 6], [1, 888], [1, 888], [1, 24, 6]] | [1, 100, 24]
-----------------------------------------------------------------------------------------------------------------------------
38.0 K    Trainable params
0         Non-trainable params
38.0 K    Total params
0.152     Total estimated model params size (MB)
11        Modules in train mode
0         Modules in eval mode

Training: |          | 0/? [00:00<?, ?it/s]

INFO: Epoch 0, global step 100: 'train_loss' reached 5.75066 (best 5.75066), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=0-step=100.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 0, global step 100: 'train_loss' reached 5.75066 (best 5.75066), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=0-step=100.ckpt' as top 1
INFO: Epoch 1, global step 200: 'train_loss' reached 4.98405 (best 4.98405), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=1-step=200.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 1, global step 200: 'train_loss' reached 4.98405 (best 4.98405), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=1-step=200.ckpt' as top 1
INFO: Epoch 2, global step 300: 'train_loss' reached 4.79441 (best 4.79441), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=2-step=300.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 2, global step 300: 'train_loss' reached 4.79441 (best 4.79441), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=2-step=300.ckpt' as top 1
INFO: Epoch 3, global step 400: 'train_loss' reached 4.75470 (best 4.75470), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=3-step=400-v2.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 3, global step 400: 'train_loss' reached 4.75470 (best 4.75470), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=3-step=400-v2.ckpt' as top 1
INFO: Epoch 4, global step 500: 'train_loss' reached 4.74469 (best 4.74469), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=4-step=500-v8.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 4, global step 500: 'train_loss' reached 4.74469 (best 4.74469), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=4-step=500-v8.ckpt' as top 1
INFO: `Trainer.fit` stopped: `max_epochs=5` reached.
INFO:lightning.pytorch.utilities.rank_zero:`Trainer.fit` stopped: `max_epochs=5` reached.

Validation rolling forecast:   0%|          | 0/7360 [00:00<?, ?window/s]

[Trial 3/8] context=336, hidden=128, dropout=0.1, lr=0.001, epochs=10, batches=100

INFO: GPU available: True (cuda), used: True
INFO:lightning.pytorch.utilities.rank_zero:GPU available: True (cuda), used: True
INFO: TPU available: False, using: 0 TPU cores
INFO:lightning.pytorch.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO: HPU available: False, using: 0 HPUs
INFO:lightning.pytorch.utilities.rank_zero:HPU available: False, using: 0 HPUs
/usr/local/lib/python3.12/dist-packages/lightning/pytorch/trainer/configuration_validator.py:70: You defined a `validation_step` but have no `val_dataloader`. Skipping val loop.
/usr/local/lib/python3.12/dist-packages/lightning/pytorch/callbacks/model_checkpoint.py:654: Checkpoint directory /content/drive/MyDrive/Electricity-Project/checkpoints exists and is not empty.
INFO: LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
INFO:lightning.pytorch.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
INFO:
  | Name  | Type        | Params | Mode  | In sizes                                                         | Out sizes
--------------------------------------------------------------------------------------------------------------------------------
0 | model | DeepARModel | 224 K  | train | [[1, 1], [1, 1], [1, 1056, 6], [1, 1056], [1, 1056], [1, 24, 6]] | [1, 100, 24]
--------------------------------------------------------------------------------------------------------------------------------
224 K     Trainable params
0         Non-trainable params
224 K     Total params
0.897     Total estimated model params size (MB)
11        Modules in train mode
0         Modules in eval mode
INFO:lightning.pytorch.callbacks.model_summary:
  | Name  | Type        | Params | Mode  | In sizes                                                         | Out sizes
--------------------------------------------------------------------------------------------------------------------------------
0 | model | DeepARModel | 224 K  | train | [[1, 1], [1, 1], [1, 1056, 6], [1, 1056], [1, 1056], [1, 24, 6]] | [1, 100, 24]
--------------------------------------------------------------------------------------------------------------------------------
224 K     Trainable params
0         Non-trainable params
224 K     Total params
0.897     Total estimated model params size (MB)
11        Modules in train mode
0         Modules in eval mode

Training: |          | 0/? [00:00<?, ?it/s]

INFO: Epoch 0, global step 100: 'train_loss' reached 5.37727 (best 5.37727), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=0-step=100.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 0, global step 100: 'train_loss' reached 5.37727 (best 5.37727), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=0-step=100.ckpt' as top 1
INFO: Epoch 1, global step 200: 'train_loss' reached 4.84767 (best 4.84767), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=1-step=200.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 1, global step 200: 'train_loss' reached 4.84767 (best 4.84767), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=1-step=200.ckpt' as top 1
INFO: Epoch 2, global step 300: 'train_loss' reached 4.73027 (best 4.73027), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=2-step=300.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 2, global step 300: 'train_loss' reached 4.73027 (best 4.73027), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=2-step=300.ckpt' as top 1
INFO: Epoch 3, global step 400: 'train_loss' reached 4.57915 (best 4.57915), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=3-step=400-v2.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 3, global step 400: 'train_loss' reached 4.57915 (best 4.57915), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=3-step=400-v2.ckpt' as top 1
INFO: Epoch 4, global step 500: 'train_loss' reached 4.52845 (best 4.52845), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=4-step=500-v9.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 4, global step 500: 'train_loss' reached 4.52845 (best 4.52845), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=4-step=500-v9.ckpt' as top 1
INFO: Epoch 5, global step 600: 'train_loss' reached 4.51082 (best 4.51082), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=5-step=600.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 5, global step 600: 'train_loss' reached 4.51082 (best 4.51082), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=5-step=600.ckpt' as top 1
INFO: Epoch 6, global step 700: 'train_loss' reached 4.45791 (best 4.45791), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=6-step=700.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 6, global step 700: 'train_loss' reached 4.45791 (best 4.45791), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=6-step=700.ckpt' as top 1
INFO: Epoch 7, global step 800: 'train_loss' was not in top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 7, global step 800: 'train_loss' was not in top 1
INFO: Epoch 8, global step 900: 'train_loss' was not in top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 8, global step 900: 'train_loss' was not in top 1
INFO: Epoch 9, global step 1000: 'train_loss' was not in top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 9, global step 1000: 'train_loss' was not in top 1
INFO: `Trainer.fit` stopped: `max_epochs=10` reached.
INFO:lightning.pytorch.utilities.rank_zero:`Trainer.fit` stopped: `max_epochs=10` reached.

Validation rolling forecast:   0%|          | 0/7360 [00:00<?, ?window/s]

[Trial 4/8] context=504, hidden=128, dropout=0.05, lr=0.0005, epochs=5, batches=50

INFO: GPU available: True (cuda), used: True
INFO:lightning.pytorch.utilities.rank_zero:GPU available: True (cuda), used: True
INFO: TPU available: False, using: 0 TPU cores
INFO:lightning.pytorch.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO: HPU available: False, using: 0 HPUs
INFO:lightning.pytorch.utilities.rank_zero:HPU available: False, using: 0 HPUs
/usr/local/lib/python3.12/dist-packages/lightning/pytorch/trainer/configuration_validator.py:70: You defined a `validation_step` but have no `val_dataloader`. Skipping val loop.
/usr/local/lib/python3.12/dist-packages/lightning/pytorch/callbacks/model_checkpoint.py:654: Checkpoint directory /content/drive/MyDrive/Electricity-Project/checkpoints exists and is not empty.
INFO: LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
INFO:lightning.pytorch.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
INFO:
  | Name  | Type        | Params | Mode  | In sizes                                                         | Out sizes
--------------------------------------------------------------------------------------------------------------------------------
0 | model | DeepARModel | 224 K  | train | [[1, 1], [1, 1], [1, 1224, 6], [1, 1224], [1, 1224], [1, 24, 6]] | [1, 100, 24]
--------------------------------------------------------------------------------------------------------------------------------
224 K     Trainable params
0         Non-trainable params
224 K     Total params
0.897     Total estimated model params size (MB)
11        Modules in train mode
0         Modules in eval mode
INFO:lightning.pytorch.callbacks.model_summary:
  | Name  | Type        | Params | Mode  | In sizes                                                         | Out sizes
--------------------------------------------------------------------------------------------------------------------------------
0 | model | DeepARModel | 224 K  | train | [[1, 1], [1, 1], [1, 1224, 6], [1, 1224], [1, 1224], [1, 24, 6]] | [1, 100, 24]
--------------------------------------------------------------------------------------------------------------------------------
224 K     Trainable params
0         Non-trainable params
224 K     Total params
0.897     Total estimated model params size (MB)
11        Modules in train mode
0         Modules in eval mode

Training: |          | 0/? [00:00<?, ?it/s]

INFO: Epoch 0, global step 50: 'train_loss' reached 5.86523 (best 5.86523), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=0-step=50.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 0, global step 50: 'train_loss' reached 5.86523 (best 5.86523), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=0-step=50.ckpt' as top 1
INFO: Epoch 1, global step 100: 'train_loss' reached 5.06774 (best 5.06774), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=1-step=100.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 1, global step 100: 'train_loss' reached 5.06774 (best 5.06774), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=1-step=100.ckpt' as top 1
INFO: Epoch 2, global step 150: 'train_loss' reached 4.94860 (best 4.94860), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=2-step=150.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 2, global step 150: 'train_loss' reached 4.94860 (best 4.94860), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=2-step=150.ckpt' as top 1
INFO: Epoch 3, global step 200: 'train_loss' reached 4.83582 (best 4.83582), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=3-step=200.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 3, global step 200: 'train_loss' reached 4.83582 (best 4.83582), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=3-step=200.ckpt' as top 1
INFO: Epoch 4, global step 250: 'train_loss' reached 4.72707 (best 4.72707), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=4-step=250-v4.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 4, global step 250: 'train_loss' reached 4.72707 (best 4.72707), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=4-step=250-v4.ckpt' as top 1
INFO: `Trainer.fit` stopped: `max_epochs=5` reached.
INFO:lightning.pytorch.utilities.rank_zero:`Trainer.fit` stopped: `max_epochs=5` reached.

Validation rolling forecast:   0%|          | 0/7360 [00:00<?, ?window/s]

[Trial 5/8] context=168, hidden=128, dropout=0.3, lr=0.001, epochs=5, batches=100

INFO: GPU available: True (cuda), used: True
INFO:lightning.pytorch.utilities.rank_zero:GPU available: True (cuda), used: True
INFO: TPU available: False, using: 0 TPU cores
INFO:lightning.pytorch.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO: HPU available: False, using: 0 HPUs
INFO:lightning.pytorch.utilities.rank_zero:HPU available: False, using: 0 HPUs
/usr/local/lib/python3.12/dist-packages/lightning/pytorch/trainer/configuration_validator.py:70: You defined a `validation_step` but have no `val_dataloader`. Skipping val loop.
/usr/local/lib/python3.12/dist-packages/lightning/pytorch/callbacks/model_checkpoint.py:654: Checkpoint directory /content/drive/MyDrive/Electricity-Project/checkpoints exists and is not empty.
INFO: LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
INFO:lightning.pytorch.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
INFO:
  | Name  | Type        | Params | Mode  | In sizes                                                      | Out sizes
-----------------------------------------------------------------------------------------------------------------------------
0 | model | DeepARModel | 224 K  | train | [[1, 1], [1, 1], [1, 888, 6], [1, 888], [1, 888], [1, 24, 6]] | [1, 100, 24]
-----------------------------------------------------------------------------------------------------------------------------
224 K     Trainable params
0         Non-trainable params
224 K     Total params
0.897     Total estimated model params size (MB)
11        Modules in train mode
0         Modules in eval mode
INFO:lightning.pytorch.callbacks.model_summary:
  | Name  | Type        | Params | Mode  | In sizes                                                      | Out sizes
-----------------------------------------------------------------------------------------------------------------------------
0 | model | DeepARModel | 224 K  | train | [[1, 1], [1, 1], [1, 888, 6], [1, 888], [1, 888], [1, 24, 6]] | [1, 100, 24]
-----------------------------------------------------------------------------------------------------------------------------
224 K     Trainable params
0         Non-trainable params
224 K     Total params
0.897     Total estimated model params size (MB)
11        Modules in train mode
0         Modules in eval mode

Training: |          | 0/? [00:00<?, ?it/s]

INFO: Epoch 0, global step 100: 'train_loss' reached 5.44204 (best 5.44204), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=0-step=100.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 0, global step 100: 'train_loss' reached 5.44204 (best 5.44204), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=0-step=100.ckpt' as top 1
INFO: Epoch 1, global step 200: 'train_loss' reached 4.88423 (best 4.88423), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=1-step=200.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 1, global step 200: 'train_loss' reached 4.88423 (best 4.88423), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=1-step=200.ckpt' as top 1
INFO: Epoch 2, global step 300: 'train_loss' reached 4.76683 (best 4.76683), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=2-step=300.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 2, global step 300: 'train_loss' reached 4.76683 (best 4.76683), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=2-step=300.ckpt' as top 1
INFO: Epoch 3, global step 400: 'train_loss' reached 4.74955 (best 4.74955), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=3-step=400-v2.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 3, global step 400: 'train_loss' reached 4.74955 (best 4.74955), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=3-step=400-v2.ckpt' as top 1
INFO: Epoch 4, global step 500: 'train_loss' reached 4.64156 (best 4.64156), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=4-step=500-v9.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 4, global step 500: 'train_loss' reached 4.64156 (best 4.64156), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=4-step=500-v9.ckpt' as top 1
INFO: `Trainer.fit` stopped: `max_epochs=5` reached.
INFO:lightning.pytorch.utilities.rank_zero:`Trainer.fit` stopped: `max_epochs=5` reached.

Validation rolling forecast:   0%|          | 0/7360 [00:00<?, ?window/s]

[Trial 6/8] context=168, hidden=96, dropout=0.1, lr=0.0002, epochs=10, batches=50

INFO: GPU available: True (cuda), used: True
INFO:lightning.pytorch.utilities.rank_zero:GPU available: True (cuda), used: True
INFO: TPU available: False, using: 0 TPU cores
INFO:lightning.pytorch.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO: HPU available: False, using: 0 HPUs
INFO:lightning.pytorch.utilities.rank_zero:HPU available: False, using: 0 HPUs
/usr/local/lib/python3.12/dist-packages/lightning/pytorch/trainer/configuration_validator.py:70: You defined a `validation_step` but have no `val_dataloader`. Skipping val loop.
/usr/local/lib/python3.12/dist-packages/lightning/pytorch/callbacks/model_checkpoint.py:654: Checkpoint directory /content/drive/MyDrive/Electricity-Project/checkpoints exists and is not empty.
INFO: LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
INFO:lightning.pytorch.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
INFO:
  | Name  | Type        | Params | Mode  | In sizes                                                      | Out sizes
-----------------------------------------------------------------------------------------------------------------------------
0 | model | DeepARModel | 131 K  | train | [[1, 1], [1, 1], [1, 888, 6], [1, 888], [1, 888], [1, 24, 6]] | [1, 100, 24]
-----------------------------------------------------------------------------------------------------------------------------
131 K     Trainable params
0         Non-trainable params
131 K     Total params
0.525     Total estimated model params size (MB)
11        Modules in train mode
0         Modules in eval mode
INFO:lightning.pytorch.callbacks.model_summary:
  | Name  | Type        | Params | Mode  | In sizes                                                      | Out sizes
-----------------------------------------------------------------------------------------------------------------------------
0 | model | DeepARModel | 131 K  | train | [[1, 1], [1, 1], [1, 888, 6], [1, 888], [1, 888], [1, 24, 6]] | [1, 100, 24]
-----------------------------------------------------------------------------------------------------------------------------
131 K     Trainable params
0         Non-trainable params
131 K     Total params
0.525     Total estimated model params size (MB)
11        Modules in train mode
0         Modules in eval mode

Training: |          | 0/? [00:00<?, ?it/s]

INFO: Epoch 0, global step 50: 'train_loss' reached 6.33119 (best 6.33119), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=0-step=50.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 0, global step 50: 'train_loss' reached 6.33119 (best 6.33119), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=0-step=50.ckpt' as top 1
INFO: Epoch 1, global step 100: 'train_loss' reached 5.56505 (best 5.56505), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=1-step=100.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 1, global step 100: 'train_loss' reached 5.56505 (best 5.56505), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=1-step=100.ckpt' as top 1
INFO: Epoch 2, global step 150: 'train_loss' reached 5.15015 (best 5.15015), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=2-step=150.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 2, global step 150: 'train_loss' reached 5.15015 (best 5.15015), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=2-step=150.ckpt' as top 1
INFO: Epoch 3, global step 200: 'train_loss' reached 5.01267 (best 5.01267), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=3-step=200.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 3, global step 200: 'train_loss' reached 5.01267 (best 5.01267), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=3-step=200.ckpt' as top 1
INFO: Epoch 4, global step 250: 'train_loss' reached 4.89691 (best 4.89691), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=4-step=250-v5.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 4, global step 250: 'train_loss' reached 4.89691 (best 4.89691), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=4-step=250-v5.ckpt' as top 1
INFO: Epoch 5, global step 300: 'train_loss' reached 4.83182 (best 4.83182), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=5-step=300.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 5, global step 300: 'train_loss' reached 4.83182 (best 4.83182), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=5-step=300.ckpt' as top 1
INFO: Epoch 6, global step 350: 'train_loss' reached 4.82775 (best 4.82775), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=6-step=350.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 6, global step 350: 'train_loss' reached 4.82775 (best 4.82775), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=6-step=350.ckpt' as top 1
INFO: Epoch 7, global step 400: 'train_loss' reached 4.77036 (best 4.77036), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=7-step=400.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 7, global step 400: 'train_loss' reached 4.77036 (best 4.77036), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=7-step=400.ckpt' as top 1
INFO: Epoch 8, global step 450: 'train_loss' reached 4.74830 (best 4.74830), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=8-step=450-v2.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 8, global step 450: 'train_loss' reached 4.74830 (best 4.74830), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=8-step=450-v2.ckpt' as top 1
INFO: Epoch 9, global step 500: 'train_loss' reached 4.73171 (best 4.73171), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=9-step=500-v13.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 9, global step 500: 'train_loss' reached 4.73171 (best 4.73171), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=9-step=500-v13.ckpt' as top 1
INFO: `Trainer.fit` stopped: `max_epochs=10` reached.
INFO:lightning.pytorch.utilities.rank_zero:`Trainer.fit` stopped: `max_epochs=10` reached.

Validation rolling forecast:   0%|          | 0/7360 [00:00<?, ?window/s]

[Trial 7/8] context=504, hidden=128, dropout=0.05, lr=0.0005, epochs=10, batches=50

INFO: GPU available: True (cuda), used: True
INFO:lightning.pytorch.utilities.rank_zero:GPU available: True (cuda), used: True
INFO: TPU available: False, using: 0 TPU cores
INFO:lightning.pytorch.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO: HPU available: False, using: 0 HPUs
INFO:lightning.pytorch.utilities.rank_zero:HPU available: False, using: 0 HPUs
/usr/local/lib/python3.12/dist-packages/lightning/pytorch/trainer/configuration_validator.py:70: You defined a `validation_step` but have no `val_dataloader`. Skipping val loop.
/usr/local/lib/python3.12/dist-packages/lightning/pytorch/callbacks/model_checkpoint.py:654: Checkpoint directory /content/drive/MyDrive/Electricity-Project/checkpoints exists and is not empty.
INFO: LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
INFO:lightning.pytorch.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
INFO:
  | Name  | Type        | Params | Mode  | In sizes                                                         | Out sizes
--------------------------------------------------------------------------------------------------------------------------------
0 | model | DeepARModel | 224 K  | train | [[1, 1], [1, 1], [1, 1224, 6], [1, 1224], [1, 1224], [1, 24, 6]] | [1, 100, 24]
--------------------------------------------------------------------------------------------------------------------------------
224 K     Trainable params
0         Non-trainable params
224 K     Total params
0.897     Total estimated model params size (MB)
11        Modules in train mode
0         Modules in eval mode
INFO:lightning.pytorch.callbacks.model_summary:
  | Name  | Type        | Params | Mode  | In sizes                                                         | Out sizes
--------------------------------------------------------------------------------------------------------------------------------
0 | model | DeepARModel | 224 K  | train | [[1, 1], [1, 1], [1, 1224, 6], [1, 1224], [1, 1224], [1, 24, 6]] | [1, 100, 24]
--------------------------------------------------------------------------------------------------------------------------------
224 K     Trainable params
0         Non-trainable params
224 K     Total params
0.897     Total estimated model params size (MB)
11        Modules in train mode
0         Modules in eval mode

Training: |          | 0/? [00:00<?, ?it/s]

INFO: Epoch 0, global step 50: 'train_loss' reached 5.90283 (best 5.90283), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=0-step=50.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 0, global step 50: 'train_loss' reached 5.90283 (best 5.90283), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=0-step=50.ckpt' as top 1
INFO: Epoch 1, global step 100: 'train_loss' reached 5.12482 (best 5.12482), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=1-step=100.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 1, global step 100: 'train_loss' reached 5.12482 (best 5.12482), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=1-step=100.ckpt' as top 1
INFO: Epoch 2, global step 150: 'train_loss' reached 4.90548 (best 4.90548), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=2-step=150.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 2, global step 150: 'train_loss' reached 4.90548 (best 4.90548), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=2-step=150.ckpt' as top 1
INFO: Epoch 3, global step 200: 'train_loss' reached 4.77346 (best 4.77346), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=3-step=200.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 3, global step 200: 'train_loss' reached 4.77346 (best 4.77346), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=3-step=200.ckpt' as top 1
INFO: Epoch 4, global step 250: 'train_loss' reached 4.74931 (best 4.74931), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=4-step=250-v5.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 4, global step 250: 'train_loss' reached 4.74931 (best 4.74931), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=4-step=250-v5.ckpt' as top 1
INFO: Epoch 5, global step 300: 'train_loss' reached 4.66044 (best 4.66044), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=5-step=300.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 5, global step 300: 'train_loss' reached 4.66044 (best 4.66044), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=5-step=300.ckpt' as top 1
INFO: Epoch 6, global step 350: 'train_loss' was not in top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 6, global step 350: 'train_loss' was not in top 1
INFO: Epoch 7, global step 400: 'train_loss' was not in top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 7, global step 400: 'train_loss' was not in top 1
INFO: Epoch 8, global step 450: 'train_loss' reached 4.53678 (best 4.53678), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=8-step=450-v2.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 8, global step 450: 'train_loss' reached 4.53678 (best 4.53678), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=8-step=450-v2.ckpt' as top 1
INFO: Epoch 9, global step 500: 'train_loss' was not in top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 9, global step 500: 'train_loss' was not in top 1
INFO: `Trainer.fit` stopped: `max_epochs=10` reached.
INFO:lightning.pytorch.utilities.rank_zero:`Trainer.fit` stopped: `max_epochs=10` reached.

Validation rolling forecast:   0%|          | 0/7360 [00:00<?, ?window/s]

[Trial 8/8] context=168, hidden=48, dropout=0.05, lr=0.0005, epochs=5, batches=100

INFO: GPU available: True (cuda), used: True
INFO:lightning.pytorch.utilities.rank_zero:GPU available: True (cuda), used: True
INFO: TPU available: False, using: 0 TPU cores
INFO:lightning.pytorch.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO: HPU available: False, using: 0 HPUs
INFO:lightning.pytorch.utilities.rank_zero:HPU available: False, using: 0 HPUs
/usr/local/lib/python3.12/dist-packages/lightning/pytorch/trainer/configuration_validator.py:70: You defined a `validation_step` but have no `val_dataloader`. Skipping val loop.
/usr/local/lib/python3.12/dist-packages/lightning/pytorch/callbacks/model_checkpoint.py:654: Checkpoint directory /content/drive/MyDrive/Electricity-Project/checkpoints exists and is not empty.
INFO: LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
INFO:lightning.pytorch.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
INFO:
  | Name  | Type        | Params | Mode  | In sizes                                                      | Out sizes
-----------------------------------------------------------------------------------------------------------------------------
0 | model | DeepARModel | 38.0 K | train | [[1, 1], [1, 1], [1, 888, 6], [1, 888], [1, 888], [1, 24, 6]] | [1, 100, 24]
-----------------------------------------------------------------------------------------------------------------------------
38.0 K    Trainable params
0         Non-trainable params
38.0 K    Total params
0.152     Total estimated model params size (MB)
11        Modules in train mode
0         Modules in eval mode
INFO:lightning.pytorch.callbacks.model_summary:
  | Name  | Type        | Params | Mode  | In sizes                                                      | Out sizes
-----------------------------------------------------------------------------------------------------------------------------
0 | model | DeepARModel | 38.0 K | train | [[1, 1], [1, 1], [1, 888, 6], [1, 888], [1, 888], [1, 24, 6]] | [1, 100, 24]
-----------------------------------------------------------------------------------------------------------------------------
38.0 K    Trainable params
0         Non-trainable params
38.0 K    Total params
0.152     Total estimated model params size (MB)
11        Modules in train mode
0         Modules in eval mode

Training: |          | 0/? [00:00<?, ?it/s]

INFO: Epoch 0, global step 100: 'train_loss' reached 5.89476 (best 5.89476), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=0-step=100.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 0, global step 100: 'train_loss' reached 5.89476 (best 5.89476), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=0-step=100.ckpt' as top 1
INFO: Epoch 1, global step 200: 'train_loss' reached 5.02179 (best 5.02179), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=1-step=200.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 1, global step 200: 'train_loss' reached 5.02179 (best 5.02179), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=1-step=200.ckpt' as top 1
INFO: Epoch 2, global step 300: 'train_loss' reached 4.86128 (best 4.86128), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=2-step=300.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 2, global step 300: 'train_loss' reached 4.86128 (best 4.86128), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=2-step=300.ckpt' as top 1
INFO: Epoch 3, global step 400: 'train_loss' reached 4.72723 (best 4.72723), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=3-step=400-v2.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 3, global step 400: 'train_loss' reached 4.72723 (best 4.72723), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=3-step=400-v2.ckpt' as top 1
INFO: Epoch 4, global step 500: 'train_loss' reached 4.67310 (best 4.67310), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=4-step=500-v10.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 4, global step 500: 'train_loss' reached 4.67310 (best 4.67310), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=4-step=500-v10.ckpt' as top 1
INFO: `Trainer.fit` stopped: `max_epochs=5` reached.
INFO:lightning.pytorch.utilities.rank_zero:`Trainer.fit` stopped: `max_epochs=5` reached.

Validation rolling forecast:   0%|          | 0/7360 [00:00<?, ?window/s]

{'summary_df':    trial  overall_mape  overall_wmape  overall_epsilon_mape  context_length  \
 0      7      9.301961       8.945734              9.299005             504
 1      8      9.735734       9.151205              9.746721             168
 2      3      9.685706       9.230726              9.674900             336
 3      1      9.698676       9.276410              9.688791             168
 4      4      9.813473       9.456947              9.818808             504
 5      2      9.866521       9.527440              9.860616             168
 6      6      9.859788       9.593709              9.861438             168
 7      5     11.133687      10.341550             11.115143             168

    hidden_size  dropout_rate  learning_rate  epochs  num_batches_per_epoch  \
 0          128          0.05         0.0005      10                     50
 1           48          0.05         0.0005       5                    100
 2          128          0.10         0.0010      10                    100
 3           96          0.20         0.0010      10                     50
 4          128          0.05         0.0005       5                     50
 5           48          0.10         0.0010       5                    100
 6           96          0.10         0.0002      10                     50
 7          128          0.30         0.0010       5                    100

    batch_size  num_parallel_samples  \
 0          64                    50
 1          64                    50
 2          64                    50
 3          64                    50
 4          64                    50
 5          64                    50
 6          64                    50
 7          64                    50

                                      prediction_path  cluster_1_mape  \
 0  outputs/deepar_random_search_1_11/trial_07/dee...        9.405956
 1  outputs/deepar_random_search_1_11/trial_08/dee...        9.888031
 2  outputs/deepar_random_search_1_11/trial_03/dee...        9.809545
 3  outputs/deepar_random_search_1_11/trial_01/dee...        9.841957
 4  outputs/deepar_random_search_1_11/trial_04/dee...        9.958859
 5  outputs/deepar_random_search_1_11/trial_02/dee...       10.016451
 6  outputs/deepar_random_search_1_11/trial_06/dee...        9.995623
 7  outputs/deepar_random_search_1_11/trial_05/dee...       11.297139

    cluster_11_mape  cluster_1_wmape  cluster_11_wmape  cluster_1_epsilon_mape  \
 0         8.007439         9.180733          5.968048                9.385229
 1         7.839970         9.439020          5.504273                9.866732
 2         8.144169         9.479271          6.081382                9.785018
 3         7.915131         9.560899          5.671630                9.820551
 4         8.003723         9.749827          5.745834                9.941856
 5         8.000202         9.822666          5.786595                9.994428
 6         8.168929         9.871522          6.073521                9.979949
 7         9.099052        10.584793          7.259398               11.265423

    cluster_11_epsilon_mape
 0                 8.235566
 1                 8.266587
 2                 8.316781
 3                 8.063748
 4                 8.301217
 5                 8.210259
 6                 8.399807
 7                 9.261695  ,
 'summary_path': 'outputs/deepar_random_search_1_11/random_search_summary.csv',
 'results_path': 'outputs/deepar_random_search_1_11/random_search_results.json',
 'best_result': {'config': {'train_path': 'train_hourly_preprocessed.parquet',
   'test_path': 'test_hourly_preprocessed.parquet',
   'cluster_path': 'clusters_3models.parquet',
   'output_dir': 'outputs/deepar_random_search_1_11/trial_01',
   'cluster_ids': (1, 11),
   'cluster_col': 'cluster_kmeans',
   'freq': 'h',
   'prediction_length': 24,
   'context_length': 168,
   'epochs': 10,
   'learning_rate': 0.001,
   'batch_size': 64,
   'num_batches_per_epoch': 50,
   'num_layers': 2,
   'hidden_size': 96,
   'dropout_rate': 0.2,
   'num_parallel_samples': 50,
   'seed': 42,
   'use_hour_of_day': True,
   'use_day_of_week': True,
   'use_weekend': True,
   'use_month': True,
   'use_holiday': True,
   'holiday_country': 'PT',
   'validation_months': 3},
  'metrics': {'overall_mape': 9.698676250787786,
   'overall_wmape': 9.276410130360896,
   'overall_epsilon_mape': 9.688790697637087,
   'cluster_mape': {'1': 9.841957274605052, '11': 7.915131010241348},
   'cluster_wmape': {'1': 9.560898734216105, '11': 5.671629651720067},
   'cluster_epsilon_mape': {'1': 9.820550892339407, '11': 8.063748296308475},
   'n_predictions': 176640,
   'n_nonzero_targets': 176490,
   'n_meters': 80,
   'meter_mape_head': {'MT_003': 5.4413381325691885,
    'MT_004': 7.1331462528287695,
    'MT_005': 12.17679703759296,
    'MT_006': 7.114616590167164,
    'MT_008': 6.0523745315319735,
    'MT_009': 14.38062639374231,
    'MT_010': 23.119524552146633,
    'MT_011': 9.23372591146576,
    'MT_016': 9.526409521953644,
    'MT_017': 6.039065732483656}},
  'dynamic_feature_names': ['hour_of_day',
   'day_of_week',
   'weekend',
   'month',
   'holiday'],
  'prediction_path': 'outputs/deepar_random_search_1_11/trial_01/deepar_clusters_1_11_validation_predictions.parquet',
  'metadata_path': 'outputs/deepar_random_search_1_11/trial_01/deepar_clusters_1_11_validation_metadata.parquet',
  'evaluation_split': 'validation',
  'train_range': ['2012-10-01 00:00:00', '2014-06-30 23:00:00'],
  'validation_range': ['2014-07-01 00:00:00', '2014-09-30 23:00:00'],
  'test_range': ['2014-10-01 00:00:00', '2014-12-31 23:00:00']}}

In [8]:
summary_path = "outputs/deepar_random_search_1_11/random_search_summary.csv"
results_path = "outputs/deepar_random_search_1_11/random_search_results.json"

summary_df = pd.read_csv(summary_path)
summary_df.head()

,trial,overall_mape,overall_wmape,overall_epsilon_mape,context_length,hidden_size,dropout_rate,learning_rate,epochs,num_batches_per_epoch,batch_size,num_parallel_samples,prediction_path,cluster_1_mape,cluster_11_mape,cluster_1_wmape,cluster_11_wmape,cluster_1_epsilon_mape,cluster_11_epsilon_mape
0,7,9.301961,8.945734,9.299005,504,128,0.05,0.0005,10,50,64,50,outputs/deepar_random_search_1_11/trial_07/dee...,9.405956,8.007439,9.180733,5.968048,9.385229,8.235566
1,8,9.735734,9.151205,9.746721,168,48,0.05,0.0005,5,100,64,50,outputs/deepar_random_search_1_11/trial_08/dee...,9.888031,7.839970,9.439020,5.504273,9.866732,8.266587
2,3,9.685706,9.230726,9.674900,336,128,0.10,0.0010,10,100,64,50,outputs/deepar_random_search_1_11/trial_03/dee...,9.809545,8.144169,9.479271,6.081382,9.785018,8.316781
3,1,9.698676,9.276410,9.688791,168,96,0.20,0.0010,10,50,64,50,outputs/deepar_random_search_1_11/trial_01/dee...,9.841957,7.915131,9.560899,5.671630,9.820551,8.063748
4,4,9.813473,9.456947,9.818808,504,128,0.05,0.0005,5,50,64,50,outputs/deepar_random_search_1_11/trial_04/dee...,9.958859,8.003723,9.749827,5.745834,9.941856,8.301217

In [9]:
best_row = summary_df.iloc[0]
best_row

trial                                                                      7
overall_mape                                                        9.301961
overall_wmape                                                       8.945734
overall_epsilon_mape                                                9.299005
context_length                                                           504
hidden_size                                                              128
dropout_rate                                                            0.05
learning_rate                                                         0.0005
epochs                                                                    10
num_batches_per_epoch                                                     50
batch_size                                                                64
num_parallel_samples                                                      50
prediction_path            outputs/deepar_random_search_1_11/trial_07/dee...
cluster_1_mape                                                      9.405956
cluster_11_mape                                                     8.007439
cluster_1_wmape                                                     9.180733
cluster_11_wmape                                                    5.968048
cluster_1_epsilon_mape                                              9.385229
cluster_11_epsilon_mape                                             8.235566
Name: 0, dtype: object

In [10]:
best_cols = [
    "overall_wmape", "overall_mape",
    "context_length", "hidden_size", "dropout_rate", "learning_rate",
    "epochs", "num_batches_per_epoch", "batch_size", "num_parallel_samples"
]

extra_cols = [
    c for c in summary_df.columns
    if c.startswith("cluster_") and c.endswith(("wmape", "mape"))
]

summary_df.loc[[0], best_cols + extra_cols].T

                                  0
overall_wmape              8.945734
overall_mape               9.301961
context_length           504.000000
hidden_size              128.000000
dropout_rate               0.050000
learning_rate              0.000500
epochs                    10.000000
num_batches_per_epoch     50.000000
batch_size                64.000000
num_parallel_samples      50.000000
cluster_1_mape             9.405956
cluster_11_mape            8.007439
cluster_1_wmape            9.180733
cluster_11_wmape           5.968048
cluster_1_epsilon_mape     9.385229
cluster_11_epsilon_mape    8.235566

In [11]:
best_pred_path = best_row["prediction_path"]
best_pred_df = pd.read_parquet(best_pred_path)
best_pred_df.head()

,timestamp,meter_id,cluster_id,y_true,y_pred,forecast_start,ape,epsilon_ape
0,2014-07-01 00:00:00,MT_003,1,6.950478,7.248984,2014-07-01,4.294762,3.754573
1,2014-07-01 01:00:00,MT_003,1,6.950478,6.874405,2014-07-01,1.094493,0.956829
2,2014-07-01 02:00:00,MT_003,1,6.950478,6.828506,2014-07-01,1.754863,1.534139
3,2014-07-01 03:00:00,MT_003,1,6.950478,7.155840,2014-07-01,2.954654,2.583021
4,2014-07-01 04:00:00,MT_003,1,6.950478,6.601655,2014-07-01,5.018695,4.387451

In [23]:
best_config = TrainConfig(
    train_path="train_hourly_preprocessed.parquet",
    test_path="test_hourly_preprocessed.parquet",
    cluster_path="clusters_3models.parquet",
    cluster_ids=CLUSTER_IDS,
    output_dir=OUTPUT_DIR,
    freq="h",
    prediction_length=24,
    context_length=int(best_row["context_length"]),
    epochs=int(best_row["epochs"]),
    learning_rate=float(best_row["learning_rate"]),
    batch_size=int(best_row["batch_size"]),
    num_batches_per_epoch=int(best_row["num_batches_per_epoch"]),
    num_layers=2,
    hidden_size=int(best_row["hidden_size"]),
    dropout_rate=float(best_row["dropout_rate"]),
    num_parallel_samples=int(best_row["num_parallel_samples"]),
    seed=42,
    use_hour_of_day=True,
    use_day_of_week=True,
    use_weekend=True,
    use_month=True,
    use_holiday=True,
    holiday_country=HOLIDAY_COUNTRY,
)

In [24]:
set_seed(best_config.seed)

train_panel, test_panel, labels = load_cluster_panels(best_config)

history_panel = pd.concat([train_panel, test_panel]).sort_index()

meta = build_metadata(history_panel, labels, best_config)

future_start = history_panel.index.max() + pd.Timedelta(hours=1)
future_end = (future_start.to_period("M") + 2).end_time.floor("h")
future_index = pd.date_range(future_start, future_end, freq="h")

print("history:", history_panel.index.min(), "->", history_panel.index.max(), history_panel.shape)
print("future :", future_index.min(), "->", future_index.max(), len(future_index))

dynamic_feat_df = build_dynamic_features(history_panel.index, future_index, best_config)

predictor = fit_predictor(history_panel, meta, dynamic_feat_df.loc[history_panel.index.union(future_index)], best_config)

print("final predictor trained")

history: 2012-10-01 00:00:00 -> 2014-12-31 23:00:00 (19728, 80)
future : 2015-01-01 00:00:00 -> 2015-03-31 23:00:00 2160

INFO: GPU available: True (cuda), used: True
INFO:lightning.pytorch.utilities.rank_zero:GPU available: True (cuda), used: True
INFO: TPU available: False, using: 0 TPU cores
INFO:lightning.pytorch.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO: HPU available: False, using: 0 HPUs
INFO:lightning.pytorch.utilities.rank_zero:HPU available: False, using: 0 HPUs
/usr/local/lib/python3.12/dist-packages/lightning/pytorch/trainer/configuration_validator.py:70: You defined a `validation_step` but have no `val_dataloader`. Skipping val loop.
/usr/local/lib/python3.12/dist-packages/lightning/pytorch/callbacks/model_checkpoint.py:654: Checkpoint directory /content/drive/MyDrive/Electricity-Project/checkpoints exists and is not empty.
INFO: LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
INFO:lightning.pytorch.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
INFO:
  | Name  | Type        | Params | Mode  | In sizes                                                         | Out sizes
--------------------------------------------------------------------------------------------------------------------------------
0 | model | DeepARModel | 224 K  | train | [[1, 1], [1, 1], [1, 1224, 6], [1, 1224], [1, 1224], [1, 24, 6]] | [1, 100, 24]
--------------------------------------------------------------------------------------------------------------------------------
224 K     Trainable params
0         Non-trainable params
224 K     Total params
0.897     Total estimated model params size (MB)
11        Modules in train mode
0         Modules in eval mode
INFO:lightning.pytorch.callbacks.model_summary:
  | Name  | Type        | Params | Mode  | In sizes                                                         | Out sizes
--------------------------------------------------------------------------------------------------------------------------------
0 | model | DeepARModel | 224 K  | train | [[1, 1], [1, 1], [1, 1224, 6], [1, 1224], [1, 1224], [1, 24, 6]] | [1, 100, 24]
--------------------------------------------------------------------------------------------------------------------------------
224 K     Trainable params
0         Non-trainable params
224 K     Total params
0.897     Total estimated model params size (MB)
11        Modules in train mode
0         Modules in eval mode

Training: |          | 0/? [00:00<?, ?it/s]

INFO: Epoch 0, global step 50: 'train_loss' reached 5.94466 (best 5.94466), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=0-step=50.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 0, global step 50: 'train_loss' reached 5.94466 (best 5.94466), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=0-step=50.ckpt' as top 1
INFO: Epoch 1, global step 100: 'train_loss' reached 5.06495 (best 5.06495), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=1-step=100.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 1, global step 100: 'train_loss' reached 5.06495 (best 5.06495), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=1-step=100.ckpt' as top 1
INFO: Epoch 2, global step 150: 'train_loss' reached 4.82090 (best 4.82090), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=2-step=150.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 2, global step 150: 'train_loss' reached 4.82090 (best 4.82090), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=2-step=150.ckpt' as top 1
INFO: Epoch 3, global step 200: 'train_loss' was not in top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 3, global step 200: 'train_loss' was not in top 1
INFO: Epoch 4, global step 250: 'train_loss' reached 4.74250 (best 4.74250), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=4-step=250-v5.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 4, global step 250: 'train_loss' reached 4.74250 (best 4.74250), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=4-step=250-v5.ckpt' as top 1
INFO: Epoch 5, global step 300: 'train_loss' was not in top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 5, global step 300: 'train_loss' was not in top 1
INFO: Epoch 6, global step 350: 'train_loss' reached 4.73911 (best 4.73911), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=6-step=350.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 6, global step 350: 'train_loss' reached 4.73911 (best 4.73911), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=6-step=350.ckpt' as top 1
INFO: Epoch 7, global step 400: 'train_loss' was not in top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 7, global step 400: 'train_loss' was not in top 1
INFO: Epoch 8, global step 450: 'train_loss' reached 4.66641 (best 4.66641), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=8-step=450-v3.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 8, global step 450: 'train_loss' reached 4.66641 (best 4.66641), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=8-step=450-v3.ckpt' as top 1
INFO: Epoch 9, global step 500: 'train_loss' reached 4.61108 (best 4.61108), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=9-step=500-v14.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 9, global step 500: 'train_loss' reached 4.61108 (best 4.61108), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=9-step=500-v14.ckpt' as top 1
INFO: `Trainer.fit` stopped: `max_epochs=10` reached.
INFO:lightning.pytorch.utilities.rank_zero:`Trainer.fit` stopped: `max_epochs=10` reached.

final predictor trained

In [27]:
future_pred_frames = []
step = best_config.prediction_length  # 24

total_windows = sum((len(future_index) + step - 1) // step for _ in history_panel.columns)
progress = tqdm(total=total_windows, desc="Future rolling forecast", unit="window")

for meter_id in history_panel.columns:
    history = history_panel[meter_id].astype(float).copy()

    static_cat = [int(meta.loc[meter_id, "cluster_code"])]
    static_real = [float(meta.loc[meter_id, "log_mean_hourly_load"])]
    cluster_id = int(meta.loc[meter_id, "cluster_id"])

    meter_future_frames = []

    for start_idx in range(0, len(future_index), step):
        end_idx = min(start_idx + step, len(future_index))
        horizon = end_idx - start_idx
        forecast_slice = future_index[start_idx:end_idx]

        record = {
            "item_id": str(meter_id),
            "start": history.index[0],
            "target": history.to_numpy(),
            "feat_static_cat": static_cat,
            "feat_static_real": static_real,
        }

        if not dynamic_feat_df.empty:
            dynamic_index = history.index.append(forecast_slice)
            record["feat_dynamic_real"] = dynamic_feat_df.loc[dynamic_index].to_numpy(dtype=float).T

        ds = ListDataset([record], freq=best_config.freq)
        forecast = next(predictor.predict(ds, num_samples=best_config.num_parallel_samples))

        pred_mean = np.asarray(forecast.mean[:horizon], dtype=float)

        meter_future_frames.append(
            pd.DataFrame(
                {
                    "timestamp": forecast_slice,
                    "meter_id": meter_id,
                    "cluster_id": cluster_id,
                    "y_pred": pred_mean,
                }
            )
        )

        history_extension = pd.Series(pred_mean, index=forecast_slice)
        history = pd.concat([history, history_extension])

        progress.update(1)

    future_pred_frames.append(pd.concat(meter_future_frames, ignore_index=True))

progress.close()

future_pred_df = pd.concat(future_pred_frames, ignore_index=True)
future_pred_df.head()

Future rolling forecast:   0%|          | 0/7200 [00:00<?, ?window/s]

            timestamp meter_id  cluster_id    y_pred
0 2015-01-01 00:00:00   MT_003           1  6.203574
1 2015-01-01 01:00:00   MT_003           1  5.253814
2 2015-01-01 02:00:00   MT_003           1  5.149548
3 2015-01-01 03:00:00   MT_003           1  5.341709
4 2015-01-01 04:00:00   MT_003           1  5.085263

In [28]:
cluster_future_df = (
    future_pred_df.groupby(["timestamp", "cluster_id"], as_index=False)["y_pred"]
    .sum()
    .sort_values(["cluster_id", "timestamp"])
)

cluster_future_df.head()

            timestamp  cluster_id        y_pred
0 2015-01-01 00:00:00           1  45621.253894
2 2015-01-01 01:00:00           1  39739.008689
4 2015-01-01 02:00:00           1  37294.647842
6 2015-01-01 03:00:00           1  37588.624073
8 2015-01-01 04:00:00           1  35235.923749

In [29]:
future_pred_path = "outputs/future_3months_predictions_1_11.parquet"
cluster_future_path = "outputs/future_3months_cluster_sum_1_11.parquet"

future_pred_df.to_parquet(future_pred_path, index=False)
cluster_future_df.to_parquet(cluster_future_path, index=False)

print("saved meter-level forecast to:", future_pred_path)
print("saved cluster-level forecast to:", cluster_future_path)

saved meter-level forecast to: outputs/future_3months_predictions_1_11.parquet
saved cluster-level forecast to: outputs/future_3months_cluster_sum_1_11.parquet

# Cluster 7

In [16]:
CLUSTER_IDS = (7,)

In [17]:
# Hyperparameters Tuning
RUN_RANDOM_SEARCH = True
N_TRIALS = 8
SEARCH_OUTPUT_DIR = None

SEARCH_SPACE = {
    'context_length_choices': (24 * 7, 24 * 14),
    'hidden_size_choices': (32, 48, 64),
    'dropout_rate_choices': (0.05, 0.1, 0.2),
    'learning_rate_choices': (1e-3, 5e-4),
    'epochs_choices': (5, 10),
    'num_batches_per_epoch_choices': (30, 50),
    'batch_size_choices': (32, 64),
    'num_parallel_samples_choices': (50,),
}

In [18]:
base_config_3 = TrainConfig(
    train_path='train_hourly_preprocessed.parquet',
    test_path='test_hourly_preprocessed.parquet',
    cluster_path='clusters_3models.parquet',
    output_dir=OUTPUT_DIR,
    cluster_ids=CLUSTER_IDS,
    prediction_length=24,
    context_length=24 * 14,
    epochs=20,
    batch_size=64,
    num_batches_per_epoch=100,
    hidden_size=64,
    dropout_rate=0.1,
    use_hour_of_day=True,
    use_day_of_week=True,
    use_weekend=True,
    use_month=True,
    use_holiday=True,
    holiday_country=HOLIDAY_COUNTRY,
)

if RUN_RANDOM_SEARCH:
    search_config_3 = RandomSearchConfig(
        n_trials=N_TRIALS,
        output_dir=SEARCH_OUTPUT_DIR,
        **SEARCH_SPACE,
    )
    results_3 = run_random_search(base_config_3, search_config_3)
else:
    results_3 = run_experiment(base_config_3)

results_3

[Trial 1/8] context=168, hidden=64, dropout=0.1, lr=0.001, epochs=10, batches=30

INFO: GPU available: True (cuda), used: True
INFO:lightning.pytorch.utilities.rank_zero:GPU available: True (cuda), used: True
INFO: TPU available: False, using: 0 TPU cores
INFO:lightning.pytorch.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO: HPU available: False, using: 0 HPUs
INFO:lightning.pytorch.utilities.rank_zero:HPU available: False, using: 0 HPUs
/usr/local/lib/python3.12/dist-packages/lightning/pytorch/trainer/configuration_validator.py:70: You defined a `validation_step` but have no `val_dataloader`. Skipping val loop.
INFO: You are using a CUDA device ('NVIDIA A100-SXM4-40GB') that has Tensor Cores. To properly utilize them, you should set `torch.set_float32_matmul_precision('medium' | 'high')` which will trade-off precision for performance. For more details, read https://pytorch.org/docs/stable/generated/torch.set_float32_matmul_precision.html#torch.set_float32_matmul_precision
INFO:lightning.pytorch.utilities.rank_zero:You are using a CUDA device ('NVIDIA A100-SXM4-40GB') that has Tensor Cores. To properly utilize them, you should set `torch.set_float32_matmul_precision('medium' | 'high')` which will trade-off precision for performance. For more details, read https://pytorch.org/docs/stable/generated/torch.set_float32_matmul_precision.html#torch.set_float32_matmul_precision
/usr/local/lib/python3.12/dist-packages/lightning/pytorch/callbacks/model_checkpoint.py:654: Checkpoint directory /content/drive/MyDrive/Electricity-Project/checkpoints exists and is not empty.
INFO: LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
INFO:lightning.pytorch.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
INFO:
  | Name  | Type        | Params | Mode  | In sizes                                                      | Out sizes
-----------------------------------------------------------------------------------------------------------------------------
0 | model | DeepARModel | 62.9 K | train | [[1, 1], [1, 1], [1, 888, 6], [1, 888], [1, 888], [1, 24, 6]] | [1, 100, 24]
-----------------------------------------------------------------------------------------------------------------------------
62.9 K    Trainable params
0         Non-trainable params
62.9 K    Total params
0.252     Total estimated model params size (MB)
11        Modules in train mode
0         Modules in eval mode
INFO:lightning.pytorch.callbacks.model_summary:
  | Name  | Type        | Params | Mode  | In sizes                                                      | Out sizes
-----------------------------------------------------------------------------------------------------------------------------
0 | model | DeepARModel | 62.9 K | train | [[1, 1], [1, 1], [1, 888, 6], [1, 888], [1, 888], [1, 24, 6]] | [1, 100, 24]
-----------------------------------------------------------------------------------------------------------------------------
62.9 K    Trainable params
0         Non-trainable params
62.9 K    Total params
0.252     Total estimated model params size (MB)
11        Modules in train mode
0         Modules in eval mode

Training: |          | 0/? [00:00<?, ?it/s]

INFO: Epoch 0, global step 30: 'train_loss' reached 7.19592 (best 7.19592), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=0-step=30.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 0, global step 30: 'train_loss' reached 7.19592 (best 7.19592), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=0-step=30.ckpt' as top 1
INFO: Epoch 1, global step 60: 'train_loss' reached 6.25648 (best 6.25648), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=1-step=60.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 1, global step 60: 'train_loss' reached 6.25648 (best 6.25648), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=1-step=60.ckpt' as top 1
INFO: Epoch 2, global step 90: 'train_loss' reached 6.08888 (best 6.08888), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=2-step=90.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 2, global step 90: 'train_loss' reached 6.08888 (best 6.08888), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=2-step=90.ckpt' as top 1
INFO: Epoch 3, global step 120: 'train_loss' reached 5.97498 (best 5.97498), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=3-step=120.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 3, global step 120: 'train_loss' reached 5.97498 (best 5.97498), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=3-step=120.ckpt' as top 1
INFO: Epoch 4, global step 150: 'train_loss' reached 5.86194 (best 5.86194), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=4-step=150.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 4, global step 150: 'train_loss' reached 5.86194 (best 5.86194), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=4-step=150.ckpt' as top 1
INFO: Epoch 5, global step 180: 'train_loss' was not in top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 5, global step 180: 'train_loss' was not in top 1
INFO: Epoch 6, global step 210: 'train_loss' was not in top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 6, global step 210: 'train_loss' was not in top 1
INFO: Epoch 7, global step 240: 'train_loss' reached 5.62589 (best 5.62589), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=7-step=240.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 7, global step 240: 'train_loss' reached 5.62589 (best 5.62589), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=7-step=240.ckpt' as top 1
INFO: Epoch 8, global step 270: 'train_loss' reached 5.55424 (best 5.55424), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=8-step=270.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 8, global step 270: 'train_loss' reached 5.55424 (best 5.55424), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=8-step=270.ckpt' as top 1
INFO: Epoch 9, global step 300: 'train_loss' reached 5.53765 (best 5.53765), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=9-step=300.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 9, global step 300: 'train_loss' reached 5.53765 (best 5.53765), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=9-step=300.ckpt' as top 1
INFO: `Trainer.fit` stopped: `max_epochs=10` reached.
INFO:lightning.pytorch.utilities.rank_zero:`Trainer.fit` stopped: `max_epochs=10` reached.

Validation rolling forecast:   0%|          | 0/1656 [00:00<?, ?window/s]

[Trial 2/8] context=168, hidden=48, dropout=0.05, lr=0.001, epochs=10, batches=30

INFO: GPU available: True (cuda), used: True
INFO:lightning.pytorch.utilities.rank_zero:GPU available: True (cuda), used: True
INFO: TPU available: False, using: 0 TPU cores
INFO:lightning.pytorch.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO: HPU available: False, using: 0 HPUs
INFO:lightning.pytorch.utilities.rank_zero:HPU available: False, using: 0 HPUs
/usr/local/lib/python3.12/dist-packages/lightning/pytorch/trainer/configuration_validator.py:70: You defined a `validation_step` but have no `val_dataloader`. Skipping val loop.
/usr/local/lib/python3.12/dist-packages/lightning/pytorch/callbacks/model_checkpoint.py:654: Checkpoint directory /content/drive/MyDrive/Electricity-Project/checkpoints exists and is not empty.
INFO: LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
INFO:lightning.pytorch.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
INFO:
  | Name  | Type        | Params | Mode  | In sizes                                                      | Out sizes
-----------------------------------------------------------------------------------------------------------------------------
0 | model | DeepARModel | 38.0 K | train | [[1, 1], [1, 1], [1, 888, 6], [1, 888], [1, 888], [1, 24, 6]] | [1, 100, 24]
-----------------------------------------------------------------------------------------------------------------------------
38.0 K    Trainable params
0         Non-trainable params
38.0 K    Total params
0.152     Total estimated model params size (MB)
11        Modules in train mode
0         Modules in eval mode
INFO:lightning.pytorch.callbacks.model_summary:
  | Name  | Type        | Params | Mode  | In sizes                                                      | Out sizes
-----------------------------------------------------------------------------------------------------------------------------
0 | model | DeepARModel | 38.0 K | train | [[1, 1], [1, 1], [1, 888, 6], [1, 888], [1, 888], [1, 24, 6]] | [1, 100, 24]
-----------------------------------------------------------------------------------------------------------------------------
38.0 K    Trainable params
0         Non-trainable params
38.0 K    Total params
0.152     Total estimated model params size (MB)
11        Modules in train mode
0         Modules in eval mode

Training: |          | 0/? [00:00<?, ?it/s]

INFO: Epoch 0, global step 30: 'train_loss' reached 7.34429 (best 7.34429), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=0-step=30.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 0, global step 30: 'train_loss' reached 7.34429 (best 7.34429), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=0-step=30.ckpt' as top 1
INFO: Epoch 1, global step 60: 'train_loss' reached 6.20513 (best 6.20513), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=1-step=60.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 1, global step 60: 'train_loss' reached 6.20513 (best 6.20513), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=1-step=60.ckpt' as top 1
INFO: Epoch 2, global step 90: 'train_loss' reached 6.19812 (best 6.19812), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=2-step=90.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 2, global step 90: 'train_loss' reached 6.19812 (best 6.19812), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=2-step=90.ckpt' as top 1
INFO: Epoch 3, global step 120: 'train_loss' reached 5.99549 (best 5.99549), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=3-step=120.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 3, global step 120: 'train_loss' reached 5.99549 (best 5.99549), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=3-step=120.ckpt' as top 1
INFO: Epoch 4, global step 150: 'train_loss' reached 5.80974 (best 5.80974), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=4-step=150.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 4, global step 150: 'train_loss' reached 5.80974 (best 5.80974), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=4-step=150.ckpt' as top 1
INFO: Epoch 5, global step 180: 'train_loss' reached 5.79957 (best 5.79957), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=5-step=180.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 5, global step 180: 'train_loss' reached 5.79957 (best 5.79957), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=5-step=180.ckpt' as top 1
INFO: Epoch 6, global step 210: 'train_loss' reached 5.74689 (best 5.74689), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=6-step=210.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 6, global step 210: 'train_loss' reached 5.74689 (best 5.74689), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=6-step=210.ckpt' as top 1
INFO: Epoch 7, global step 240: 'train_loss' reached 5.70268 (best 5.70268), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=7-step=240.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 7, global step 240: 'train_loss' reached 5.70268 (best 5.70268), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=7-step=240.ckpt' as top 1
INFO: Epoch 8, global step 270: 'train_loss' reached 5.62518 (best 5.62518), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=8-step=270.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 8, global step 270: 'train_loss' reached 5.62518 (best 5.62518), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=8-step=270.ckpt' as top 1
INFO: Epoch 9, global step 300: 'train_loss' was not in top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 9, global step 300: 'train_loss' was not in top 1
INFO: `Trainer.fit` stopped: `max_epochs=10` reached.
INFO:lightning.pytorch.utilities.rank_zero:`Trainer.fit` stopped: `max_epochs=10` reached.

Validation rolling forecast:   0%|          | 0/1656 [00:00<?, ?window/s]

[Trial 3/8] context=168, hidden=32, dropout=0.2, lr=0.0005, epochs=10, batches=50

INFO: GPU available: True (cuda), used: True
INFO:lightning.pytorch.utilities.rank_zero:GPU available: True (cuda), used: True
INFO: TPU available: False, using: 0 TPU cores
INFO:lightning.pytorch.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO: HPU available: False, using: 0 HPUs
INFO:lightning.pytorch.utilities.rank_zero:HPU available: False, using: 0 HPUs
/usr/local/lib/python3.12/dist-packages/lightning/pytorch/trainer/configuration_validator.py:70: You defined a `validation_step` but have no `val_dataloader`. Skipping val loop.
/usr/local/lib/python3.12/dist-packages/lightning/pytorch/callbacks/model_checkpoint.py:654: Checkpoint directory /content/drive/MyDrive/Electricity-Project/checkpoints exists and is not empty.
INFO: LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
INFO:lightning.pytorch.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
INFO:
  | Name  | Type        | Params | Mode  | In sizes                                                      | Out sizes
-----------------------------------------------------------------------------------------------------------------------------
0 | model | DeepARModel | 19.2 K | train | [[1, 1], [1, 1], [1, 888, 6], [1, 888], [1, 888], [1, 24, 6]] | [1, 100, 24]
-----------------------------------------------------------------------------------------------------------------------------
19.2 K    Trainable params
0         Non-trainable params
19.2 K    Total params
0.077     Total estimated model params size (MB)
11        Modules in train mode
0         Modules in eval mode
INFO:lightning.pytorch.callbacks.model_summary:
  | Name  | Type        | Params | Mode  | In sizes                                                      | Out sizes
-----------------------------------------------------------------------------------------------------------------------------
0 | model | DeepARModel | 19.2 K | train | [[1, 1], [1, 1], [1, 888, 6], [1, 888], [1, 888], [1, 24, 6]] | [1, 100, 24]
-----------------------------------------------------------------------------------------------------------------------------
19.2 K    Trainable params
0         Non-trainable params
19.2 K    Total params
0.077     Total estimated model params size (MB)
11        Modules in train mode
0         Modules in eval mode

Training: |          | 0/? [00:00<?, ?it/s]

INFO: Epoch 0, global step 50: 'train_loss' reached 7.62386 (best 7.62386), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=0-step=50.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 0, global step 50: 'train_loss' reached 7.62386 (best 7.62386), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=0-step=50.ckpt' as top 1
INFO: Epoch 1, global step 100: 'train_loss' reached 6.67660 (best 6.67660), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=1-step=100.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 1, global step 100: 'train_loss' reached 6.67660 (best 6.67660), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=1-step=100.ckpt' as top 1
INFO: Epoch 2, global step 150: 'train_loss' reached 6.19311 (best 6.19311), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=2-step=150.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 2, global step 150: 'train_loss' reached 6.19311 (best 6.19311), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=2-step=150.ckpt' as top 1
INFO: Epoch 3, global step 200: 'train_loss' reached 6.04783 (best 6.04783), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=3-step=200.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 3, global step 200: 'train_loss' reached 6.04783 (best 6.04783), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=3-step=200.ckpt' as top 1
INFO: Epoch 4, global step 250: 'train_loss' reached 5.91529 (best 5.91529), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=4-step=250-v6.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 4, global step 250: 'train_loss' reached 5.91529 (best 5.91529), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=4-step=250-v6.ckpt' as top 1
INFO: Epoch 5, global step 300: 'train_loss' reached 5.68767 (best 5.68767), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=5-step=300.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 5, global step 300: 'train_loss' reached 5.68767 (best 5.68767), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=5-step=300.ckpt' as top 1
INFO: Epoch 6, global step 350: 'train_loss' reached 5.62130 (best 5.62130), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=6-step=350.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 6, global step 350: 'train_loss' reached 5.62130 (best 5.62130), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=6-step=350.ckpt' as top 1
INFO: Epoch 7, global step 400: 'train_loss' reached 5.60653 (best 5.60653), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=7-step=400.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 7, global step 400: 'train_loss' reached 5.60653 (best 5.60653), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=7-step=400.ckpt' as top 1
INFO: Epoch 8, global step 450: 'train_loss' was not in top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 8, global step 450: 'train_loss' was not in top 1
INFO: Epoch 9, global step 500: 'train_loss' reached 5.53760 (best 5.53760), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=9-step=500-v18.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 9, global step 500: 'train_loss' reached 5.53760 (best 5.53760), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=9-step=500-v18.ckpt' as top 1
INFO: `Trainer.fit` stopped: `max_epochs=10` reached.
INFO:lightning.pytorch.utilities.rank_zero:`Trainer.fit` stopped: `max_epochs=10` reached.

Validation rolling forecast:   0%|          | 0/1656 [00:00<?, ?window/s]

[Trial 4/8] context=336, hidden=32, dropout=0.05, lr=0.001, epochs=10, batches=50

INFO: GPU available: True (cuda), used: True
INFO:lightning.pytorch.utilities.rank_zero:GPU available: True (cuda), used: True
INFO: TPU available: False, using: 0 TPU cores
INFO:lightning.pytorch.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO: HPU available: False, using: 0 HPUs
INFO:lightning.pytorch.utilities.rank_zero:HPU available: False, using: 0 HPUs
/usr/local/lib/python3.12/dist-packages/lightning/pytorch/trainer/configuration_validator.py:70: You defined a `validation_step` but have no `val_dataloader`. Skipping val loop.
/usr/local/lib/python3.12/dist-packages/lightning/pytorch/callbacks/model_checkpoint.py:654: Checkpoint directory /content/drive/MyDrive/Electricity-Project/checkpoints exists and is not empty.
INFO: LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
INFO:lightning.pytorch.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
INFO:
  | Name  | Type        | Params | Mode  | In sizes                                                         | Out sizes
--------------------------------------------------------------------------------------------------------------------------------
0 | model | DeepARModel | 19.2 K | train | [[1, 1], [1, 1], [1, 1056, 6], [1, 1056], [1, 1056], [1, 24, 6]] | [1, 100, 24]
--------------------------------------------------------------------------------------------------------------------------------
19.2 K    Trainable params
0         Non-trainable params
19.2 K    Total params
0.077     Total estimated model params size (MB)
11        Modules in train mode
0         Modules in eval mode
INFO:lightning.pytorch.callbacks.model_summary:
  | Name  | Type        | Params | Mode  | In sizes                                                         | Out sizes
--------------------------------------------------------------------------------------------------------------------------------
0 | model | DeepARModel | 19.2 K | train | [[1, 1], [1, 1], [1, 1056, 6], [1, 1056], [1, 1056], [1, 24, 6]] | [1, 100, 24]
--------------------------------------------------------------------------------------------------------------------------------
19.2 K    Trainable params
0         Non-trainable params
19.2 K    Total params
0.077     Total estimated model params size (MB)
11        Modules in train mode
0         Modules in eval mode

Training: |          | 0/? [00:00<?, ?it/s]

INFO: Epoch 0, global step 50: 'train_loss' reached 7.22592 (best 7.22592), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=0-step=50.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 0, global step 50: 'train_loss' reached 7.22592 (best 7.22592), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=0-step=50.ckpt' as top 1
INFO: Epoch 1, global step 100: 'train_loss' reached 6.14804 (best 6.14804), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=1-step=100.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 1, global step 100: 'train_loss' reached 6.14804 (best 6.14804), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=1-step=100.ckpt' as top 1
INFO: Epoch 2, global step 150: 'train_loss' reached 5.89889 (best 5.89889), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=2-step=150.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 2, global step 150: 'train_loss' reached 5.89889 (best 5.89889), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=2-step=150.ckpt' as top 1
INFO: Epoch 3, global step 200: 'train_loss' reached 5.69762 (best 5.69762), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=3-step=200.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 3, global step 200: 'train_loss' reached 5.69762 (best 5.69762), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=3-step=200.ckpt' as top 1
INFO: Epoch 4, global step 250: 'train_loss' reached 5.55421 (best 5.55421), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=4-step=250-v6.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 4, global step 250: 'train_loss' reached 5.55421 (best 5.55421), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=4-step=250-v6.ckpt' as top 1
INFO: Epoch 5, global step 300: 'train_loss' was not in top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 5, global step 300: 'train_loss' was not in top 1
INFO: Epoch 6, global step 350: 'train_loss' reached 5.53092 (best 5.53092), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=6-step=350.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 6, global step 350: 'train_loss' reached 5.53092 (best 5.53092), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=6-step=350.ckpt' as top 1
INFO: Epoch 7, global step 400: 'train_loss' reached 5.46956 (best 5.46956), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=7-step=400.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 7, global step 400: 'train_loss' reached 5.46956 (best 5.46956), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=7-step=400.ckpt' as top 1
INFO: Epoch 8, global step 450: 'train_loss' reached 5.35063 (best 5.35063), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=8-step=450-v4.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 8, global step 450: 'train_loss' reached 5.35063 (best 5.35063), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=8-step=450-v4.ckpt' as top 1
INFO: Epoch 9, global step 500: 'train_loss' was not in top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 9, global step 500: 'train_loss' was not in top 1
INFO: `Trainer.fit` stopped: `max_epochs=10` reached.
INFO:lightning.pytorch.utilities.rank_zero:`Trainer.fit` stopped: `max_epochs=10` reached.

Validation rolling forecast:   0%|          | 0/1656 [00:00<?, ?window/s]

[Trial 5/8] context=168, hidden=64, dropout=0.05, lr=0.0005, epochs=5, batches=50

INFO: GPU available: True (cuda), used: True
INFO:lightning.pytorch.utilities.rank_zero:GPU available: True (cuda), used: True
INFO: TPU available: False, using: 0 TPU cores
INFO:lightning.pytorch.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO: HPU available: False, using: 0 HPUs
INFO:lightning.pytorch.utilities.rank_zero:HPU available: False, using: 0 HPUs
/usr/local/lib/python3.12/dist-packages/lightning/pytorch/trainer/configuration_validator.py:70: You defined a `validation_step` but have no `val_dataloader`. Skipping val loop.
/usr/local/lib/python3.12/dist-packages/lightning/pytorch/callbacks/model_checkpoint.py:654: Checkpoint directory /content/drive/MyDrive/Electricity-Project/checkpoints exists and is not empty.
INFO: LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
INFO:lightning.pytorch.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
INFO:
  | Name  | Type        | Params | Mode  | In sizes                                                      | Out sizes
-----------------------------------------------------------------------------------------------------------------------------
0 | model | DeepARModel | 62.9 K | train | [[1, 1], [1, 1], [1, 888, 6], [1, 888], [1, 888], [1, 24, 6]] | [1, 100, 24]
-----------------------------------------------------------------------------------------------------------------------------
62.9 K    Trainable params
0         Non-trainable params
62.9 K    Total params
0.252     Total estimated model params size (MB)
11        Modules in train mode
0         Modules in eval mode
INFO:lightning.pytorch.callbacks.model_summary:
  | Name  | Type        | Params | Mode  | In sizes                                                      | Out sizes
-----------------------------------------------------------------------------------------------------------------------------
0 | model | DeepARModel | 62.9 K | train | [[1, 1], [1, 1], [1, 888, 6], [1, 888], [1, 888], [1, 24, 6]] | [1, 100, 24]
-----------------------------------------------------------------------------------------------------------------------------
62.9 K    Trainable params
0         Non-trainable params
62.9 K    Total params
0.252     Total estimated model params size (MB)
11        Modules in train mode
0         Modules in eval mode

Training: |          | 0/? [00:00<?, ?it/s]

INFO: Epoch 0, global step 50: 'train_loss' reached 7.08107 (best 7.08107), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=0-step=50.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 0, global step 50: 'train_loss' reached 7.08107 (best 7.08107), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=0-step=50.ckpt' as top 1
INFO: Epoch 1, global step 100: 'train_loss' reached 6.13243 (best 6.13243), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=1-step=100.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 1, global step 100: 'train_loss' reached 6.13243 (best 6.13243), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=1-step=100.ckpt' as top 1
INFO: Epoch 2, global step 150: 'train_loss' reached 5.87687 (best 5.87687), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=2-step=150.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 2, global step 150: 'train_loss' reached 5.87687 (best 5.87687), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=2-step=150.ckpt' as top 1
INFO: Epoch 3, global step 200: 'train_loss' reached 5.76365 (best 5.76365), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=3-step=200.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 3, global step 200: 'train_loss' reached 5.76365 (best 5.76365), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=3-step=200.ckpt' as top 1
INFO: Epoch 4, global step 250: 'train_loss' reached 5.67474 (best 5.67474), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=4-step=250-v6.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 4, global step 250: 'train_loss' reached 5.67474 (best 5.67474), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=4-step=250-v6.ckpt' as top 1
INFO: `Trainer.fit` stopped: `max_epochs=5` reached.
INFO:lightning.pytorch.utilities.rank_zero:`Trainer.fit` stopped: `max_epochs=5` reached.

Validation rolling forecast:   0%|          | 0/1656 [00:00<?, ?window/s]

[Trial 6/8] context=168, hidden=64, dropout=0.2, lr=0.001, epochs=10, batches=50

INFO: GPU available: True (cuda), used: True
INFO:lightning.pytorch.utilities.rank_zero:GPU available: True (cuda), used: True
INFO: TPU available: False, using: 0 TPU cores
INFO:lightning.pytorch.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO: HPU available: False, using: 0 HPUs
INFO:lightning.pytorch.utilities.rank_zero:HPU available: False, using: 0 HPUs
/usr/local/lib/python3.12/dist-packages/lightning/pytorch/trainer/configuration_validator.py:70: You defined a `validation_step` but have no `val_dataloader`. Skipping val loop.
/usr/local/lib/python3.12/dist-packages/lightning/pytorch/callbacks/model_checkpoint.py:654: Checkpoint directory /content/drive/MyDrive/Electricity-Project/checkpoints exists and is not empty.
INFO: LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
INFO:lightning.pytorch.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
INFO:
  | Name  | Type        | Params | Mode  | In sizes                                                      | Out sizes
-----------------------------------------------------------------------------------------------------------------------------
0 | model | DeepARModel | 62.9 K | train | [[1, 1], [1, 1], [1, 888, 6], [1, 888], [1, 888], [1, 24, 6]] | [1, 100, 24]
-----------------------------------------------------------------------------------------------------------------------------
62.9 K    Trainable params
0         Non-trainable params
62.9 K    Total params
0.252     Total estimated model params size (MB)
11        Modules in train mode
0         Modules in eval mode
INFO:lightning.pytorch.callbacks.model_summary:
  | Name  | Type        | Params | Mode  | In sizes                                                      | Out sizes
-----------------------------------------------------------------------------------------------------------------------------
0 | model | DeepARModel | 62.9 K | train | [[1, 1], [1, 1], [1, 888, 6], [1, 888], [1, 888], [1, 24, 6]] | [1, 100, 24]
-----------------------------------------------------------------------------------------------------------------------------
62.9 K    Trainable params
0         Non-trainable params
62.9 K    Total params
0.252     Total estimated model params size (MB)
11        Modules in train mode
0         Modules in eval mode

Training: |          | 0/? [00:00<?, ?it/s]

INFO: Epoch 0, global step 50: 'train_loss' reached 6.88033 (best 6.88033), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=0-step=50.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 0, global step 50: 'train_loss' reached 6.88033 (best 6.88033), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=0-step=50.ckpt' as top 1
INFO: Epoch 1, global step 100: 'train_loss' reached 6.14727 (best 6.14727), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=1-step=100.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 1, global step 100: 'train_loss' reached 6.14727 (best 6.14727), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=1-step=100.ckpt' as top 1
INFO: Epoch 2, global step 150: 'train_loss' reached 5.94599 (best 5.94599), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=2-step=150.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 2, global step 150: 'train_loss' reached 5.94599 (best 5.94599), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=2-step=150.ckpt' as top 1
INFO: Epoch 3, global step 200: 'train_loss' reached 5.73182 (best 5.73182), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=3-step=200.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 3, global step 200: 'train_loss' reached 5.73182 (best 5.73182), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=3-step=200.ckpt' as top 1
INFO: Epoch 4, global step 250: 'train_loss' reached 5.68734 (best 5.68734), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=4-step=250-v7.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 4, global step 250: 'train_loss' reached 5.68734 (best 5.68734), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=4-step=250-v7.ckpt' as top 1
INFO: Epoch 5, global step 300: 'train_loss' reached 5.49123 (best 5.49123), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=5-step=300.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 5, global step 300: 'train_loss' reached 5.49123 (best 5.49123), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=5-step=300.ckpt' as top 1
INFO: Epoch 6, global step 350: 'train_loss' was not in top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 6, global step 350: 'train_loss' was not in top 1
INFO: Epoch 7, global step 400: 'train_loss' was not in top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 7, global step 400: 'train_loss' was not in top 1
INFO: Epoch 8, global step 450: 'train_loss' reached 5.42318 (best 5.42318), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=8-step=450-v5.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 8, global step 450: 'train_loss' reached 5.42318 (best 5.42318), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=8-step=450-v5.ckpt' as top 1
INFO: Epoch 9, global step 500: 'train_loss' was not in top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 9, global step 500: 'train_loss' was not in top 1
INFO: `Trainer.fit` stopped: `max_epochs=10` reached.
INFO:lightning.pytorch.utilities.rank_zero:`Trainer.fit` stopped: `max_epochs=10` reached.

Validation rolling forecast:   0%|          | 0/1656 [00:00<?, ?window/s]

[Trial 7/8] context=168, hidden=32, dropout=0.05, lr=0.001, epochs=5, batches=50

INFO: GPU available: True (cuda), used: True
INFO:lightning.pytorch.utilities.rank_zero:GPU available: True (cuda), used: True
INFO: TPU available: False, using: 0 TPU cores
INFO:lightning.pytorch.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO: HPU available: False, using: 0 HPUs
INFO:lightning.pytorch.utilities.rank_zero:HPU available: False, using: 0 HPUs
/usr/local/lib/python3.12/dist-packages/lightning/pytorch/trainer/configuration_validator.py:70: You defined a `validation_step` but have no `val_dataloader`. Skipping val loop.
/usr/local/lib/python3.12/dist-packages/lightning/pytorch/callbacks/model_checkpoint.py:654: Checkpoint directory /content/drive/MyDrive/Electricity-Project/checkpoints exists and is not empty.
INFO: LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
INFO:lightning.pytorch.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
INFO:
  | Name  | Type        | Params | Mode  | In sizes                                                      | Out sizes
-----------------------------------------------------------------------------------------------------------------------------
0 | model | DeepARModel | 19.2 K | train | [[1, 1], [1, 1], [1, 888, 6], [1, 888], [1, 888], [1, 24, 6]] | [1, 100, 24]
-----------------------------------------------------------------------------------------------------------------------------
19.2 K    Trainable params
0         Non-trainable params
19.2 K    Total params
0.077     Total estimated model params size (MB)
11        Modules in train mode
0         Modules in eval mode
INFO:lightning.pytorch.callbacks.model_summary:
  | Name  | Type        | Params | Mode  | In sizes                                                      | Out sizes
-----------------------------------------------------------------------------------------------------------------------------
0 | model | DeepARModel | 19.2 K | train | [[1, 1], [1, 1], [1, 888, 6], [1, 888], [1, 888], [1, 24, 6]] | [1, 100, 24]
-----------------------------------------------------------------------------------------------------------------------------
19.2 K    Trainable params
0         Non-trainable params
19.2 K    Total params
0.077     Total estimated model params size (MB)
11        Modules in train mode
0         Modules in eval mode

Training: |          | 0/? [00:00<?, ?it/s]

INFO: Epoch 0, global step 50: 'train_loss' reached 6.88367 (best 6.88367), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=0-step=50.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 0, global step 50: 'train_loss' reached 6.88367 (best 6.88367), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=0-step=50.ckpt' as top 1
INFO: Epoch 1, global step 100: 'train_loss' reached 6.22228 (best 6.22228), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=1-step=100.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 1, global step 100: 'train_loss' reached 6.22228 (best 6.22228), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=1-step=100.ckpt' as top 1
INFO: Epoch 2, global step 150: 'train_loss' reached 5.96139 (best 5.96139), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=2-step=150.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 2, global step 150: 'train_loss' reached 5.96139 (best 5.96139), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=2-step=150.ckpt' as top 1
INFO: Epoch 3, global step 200: 'train_loss' reached 5.78463 (best 5.78463), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=3-step=200.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 3, global step 200: 'train_loss' reached 5.78463 (best 5.78463), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=3-step=200.ckpt' as top 1
INFO: Epoch 4, global step 250: 'train_loss' reached 5.70523 (best 5.70523), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=4-step=250-v7.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 4, global step 250: 'train_loss' reached 5.70523 (best 5.70523), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=4-step=250-v7.ckpt' as top 1
INFO: `Trainer.fit` stopped: `max_epochs=5` reached.
INFO:lightning.pytorch.utilities.rank_zero:`Trainer.fit` stopped: `max_epochs=5` reached.

Validation rolling forecast:   0%|          | 0/1656 [00:00<?, ?window/s]

[Trial 8/8] context=168, hidden=48, dropout=0.05, lr=0.001, epochs=5, batches=30

INFO: GPU available: True (cuda), used: True
INFO:lightning.pytorch.utilities.rank_zero:GPU available: True (cuda), used: True
INFO: TPU available: False, using: 0 TPU cores
INFO:lightning.pytorch.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO: HPU available: False, using: 0 HPUs
INFO:lightning.pytorch.utilities.rank_zero:HPU available: False, using: 0 HPUs
/usr/local/lib/python3.12/dist-packages/lightning/pytorch/trainer/configuration_validator.py:70: You defined a `validation_step` but have no `val_dataloader`. Skipping val loop.
/usr/local/lib/python3.12/dist-packages/lightning/pytorch/callbacks/model_checkpoint.py:654: Checkpoint directory /content/drive/MyDrive/Electricity-Project/checkpoints exists and is not empty.
INFO: LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
INFO:lightning.pytorch.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
INFO:
  | Name  | Type        | Params | Mode  | In sizes                                                      | Out sizes
-----------------------------------------------------------------------------------------------------------------------------
0 | model | DeepARModel | 38.0 K | train | [[1, 1], [1, 1], [1, 888, 6], [1, 888], [1, 888], [1, 24, 6]] | [1, 100, 24]
-----------------------------------------------------------------------------------------------------------------------------
38.0 K    Trainable params
0         Non-trainable params
38.0 K    Total params
0.152     Total estimated model params size (MB)
11        Modules in train mode
0         Modules in eval mode
INFO:lightning.pytorch.callbacks.model_summary:
  | Name  | Type        | Params | Mode  | In sizes                                                      | Out sizes
-----------------------------------------------------------------------------------------------------------------------------
0 | model | DeepARModel | 38.0 K | train | [[1, 1], [1, 1], [1, 888, 6], [1, 888], [1, 888], [1, 24, 6]] | [1, 100, 24]
-----------------------------------------------------------------------------------------------------------------------------
38.0 K    Trainable params
0         Non-trainable params
38.0 K    Total params
0.152     Total estimated model params size (MB)
11        Modules in train mode
0         Modules in eval mode

Training: |          | 0/? [00:00<?, ?it/s]

INFO: Epoch 0, global step 30: 'train_loss' reached 7.23406 (best 7.23406), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=0-step=30.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 0, global step 30: 'train_loss' reached 7.23406 (best 7.23406), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=0-step=30.ckpt' as top 1
INFO: Epoch 1, global step 60: 'train_loss' reached 6.19536 (best 6.19536), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=1-step=60.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 1, global step 60: 'train_loss' reached 6.19536 (best 6.19536), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=1-step=60.ckpt' as top 1
INFO: Epoch 2, global step 90: 'train_loss' reached 6.14735 (best 6.14735), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=2-step=90.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 2, global step 90: 'train_loss' reached 6.14735 (best 6.14735), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=2-step=90.ckpt' as top 1
INFO: Epoch 3, global step 120: 'train_loss' reached 5.89624 (best 5.89624), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=3-step=120.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 3, global step 120: 'train_loss' reached 5.89624 (best 5.89624), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=3-step=120.ckpt' as top 1
INFO: Epoch 4, global step 150: 'train_loss' was not in top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 4, global step 150: 'train_loss' was not in top 1
INFO: `Trainer.fit` stopped: `max_epochs=5` reached.
INFO:lightning.pytorch.utilities.rank_zero:`Trainer.fit` stopped: `max_epochs=5` reached.

Validation rolling forecast:   0%|          | 0/1656 [00:00<?, ?window/s]

{'summary_df':    trial  overall_mape  overall_wmape  overall_epsilon_mape  context_length  \
 0      1      5.703177       4.889144             55.669890             168
 1      4      5.676155       4.977045             52.239740             336
 2      3      5.874045       5.010893             55.058443             168
 3      7      5.894007       5.254286             52.773744             168
 4      2      6.695483       5.800654             56.658923             168
 5      6      6.745140       5.963651             56.108672             168
 6      5      6.739250       5.988199             51.796970             168
 7      8     11.866295      10.381764             71.197272             168

    hidden_size  dropout_rate  learning_rate  epochs  num_batches_per_epoch  \
 0           64          0.10         0.0010      10                     30
 1           32          0.05         0.0010      10                     50
 2           32          0.20         0.0005      10                     50
 3           32          0.05         0.0010       5                     50
 4           48          0.05         0.0010      10                     30
 5           64          0.20         0.0010      10                     50
 6           64          0.05         0.0005       5                     50
 7           48          0.05         0.0010       5                     30

    batch_size  num_parallel_samples  \
 0          32                    50
 1          32                    50
 2          32                    50
 3          32                    50
 4          64                    50
 5          32                    50
 6          64                    50
 7          64                    50

                                      prediction_path  cluster_7_mape  \
 0  outputs/deepar_random_search_7/trial_01/deepar...        5.703177
 1  outputs/deepar_random_search_7/trial_04/deepar...        5.676155
 2  outputs/deepar_random_search_7/trial_03/deepar...        5.874045
 3  outputs/deepar_random_search_7/trial_07/deepar...        5.894007
 4  outputs/deepar_random_search_7/trial_02/deepar...        6.695483
 5  outputs/deepar_random_search_7/trial_06/deepar...        6.745140
 6  outputs/deepar_random_search_7/trial_05/deepar...        6.739250
 7  outputs/deepar_random_search_7/trial_08/deepar...       11.866295

    cluster_7_wmape  cluster_7_epsilon_mape
 0         4.889144               55.669890
 1         4.977045               52.239740
 2         5.010893               55.058443
 3         5.254286               52.773744
 4         5.800654               56.658923
 5         5.963651               56.108672
 6         5.988199               51.796970
 7        10.381764               71.197272  ,
 'summary_path': 'outputs/deepar_random_search_7/random_search_summary.csv',
 'results_path': 'outputs/deepar_random_search_7/random_search_results.json',
 'best_result': {'config': {'train_path': 'train_hourly_preprocessed.parquet',
   'test_path': 'test_hourly_preprocessed.parquet',
   'cluster_path': 'clusters_3models.parquet',
   'output_dir': 'outputs/deepar_random_search_7/trial_01',
   'cluster_ids': (7,),
   'cluster_col': 'cluster_kmeans',
   'freq': 'h',
   'prediction_length': 24,
   'context_length': 168,
   'epochs': 10,
   'learning_rate': 0.001,
   'batch_size': 32,
   'num_batches_per_epoch': 30,
   'num_layers': 2,
   'hidden_size': 64,
   'dropout_rate': 0.1,
   'num_parallel_samples': 50,
   'seed': 42,
   'use_hour_of_day': True,
   'use_day_of_week': True,
   'use_weekend': True,
   'use_month': True,
   'use_holiday': True,
   'holiday_country': 'PT',
   'validation_months': 3},
  'metrics': {'overall_mape': 5.703176680394366,
   'overall_wmape': 4.889144458326477,
   'overall_epsilon_mape': 55.66989004988901,
   'cluster_mape': {'7': 5.703176680394367},
   'cluster_wmape': {'7': 4.889144458326477},
   'cluster_epsilon_mape': {'7': 55.66989004988901},
   'n_predictions': 39744,
   'n_nonzero_targets': 39741,
   'n_meters': 18,
   'meter_mape_head': {'MT_002': 7.0797683393486786,
    'MT_068': 8.323783766728358,
    'MT_091': 9.912858103796273,
    'MT_119': 8.602850210649365,
    'MT_138': 7.775816948438253,
    'MT_143': 10.232499069831187,
    'MT_145': 2.5077431476762104,
    'MT_146': 1.9756301406878876,
    'MT_147': 2.149645408347823,
    'MT_148': 2.1879360493345557}},
  'dynamic_feature_names': ['hour_of_day',
   'day_of_week',
   'weekend',
   'month',
   'holiday'],
  'prediction_path': 'outputs/deepar_random_search_7/trial_01/deepar_clusters_7_validation_predictions.parquet',
  'metadata_path': 'outputs/deepar_random_search_7/trial_01/deepar_clusters_7_validation_metadata.parquet',
  'evaluation_split': 'validation',
  'train_range': ['2012-10-01 00:00:00', '2014-06-30 23:00:00'],
  'validation_range': ['2014-07-01 00:00:00', '2014-09-30 23:00:00'],
  'test_range': ['2014-10-01 00:00:00', '2014-12-31 23:00:00']}}

In [19]:
summary_path = "outputs/deepar_random_search_7/random_search_summary.csv"
results_path = "outputs/deepar_random_search_7/random_search_results.json"

summary_df = pd.read_csv(summary_path)
summary_df.head()

,trial,overall_mape,overall_wmape,overall_epsilon_mape,context_length,hidden_size,dropout_rate,learning_rate,epochs,num_batches_per_epoch,batch_size,num_parallel_samples,prediction_path,cluster_7_mape,cluster_7_wmape,cluster_7_epsilon_mape
0,1,5.703177,4.889144,55.669890,168,64,0.10,0.0010,10,30,32,50,outputs/deepar_random_search_7/trial_01/deepar...,5.703177,4.889144,55.669890
1,4,5.676155,4.977045,52.239740,336,32,0.05,0.0010,10,50,32,50,outputs/deepar_random_search_7/trial_04/deepar...,5.676155,4.977045,52.239740
2,3,5.874045,5.010893,55.058443,168,32,0.20,0.0005,10,50,32,50,outputs/deepar_random_search_7/trial_03/deepar...,5.874045,5.010893,55.058443
3,7,5.894007,5.254286,52.773744,168,32,0.05,0.0010,5,50,32,50,outputs/deepar_random_search_7/trial_07/deepar...,5.894007,5.254286,52.773744
4,2,6.695483,5.800654,56.658923,168,48,0.05,0.0010,10,30,64,50,outputs/deepar_random_search_7/trial_02/deepar...,6.695483,5.800654,56.658923

In [20]:
best_row = summary_df.iloc[0]
best_row

trial                                                                     1
overall_mape                                                       5.703177
overall_wmape                                                      4.889144
overall_epsilon_mape                                               55.66989
context_length                                                          168
hidden_size                                                              64
dropout_rate                                                            0.1
learning_rate                                                         0.001
epochs                                                                   10
num_batches_per_epoch                                                    30
batch_size                                                               32
num_parallel_samples                                                     50
prediction_path           outputs/deepar_random_search_7/trial_01/deepar...
cluster_7_mape                                                     5.703177
cluster_7_wmape                                                    4.889144
cluster_7_epsilon_mape                                             55.66989
Name: 0, dtype: object

In [21]:
best_cols = [
    "overall_wmape", "overall_mape",
    "context_length", "hidden_size", "dropout_rate", "learning_rate",
    "epochs", "num_batches_per_epoch", "batch_size", "num_parallel_samples"
]

extra_cols = [
    c for c in summary_df.columns
    if c.startswith("cluster_") and c.endswith(("wmape", "mape"))
]

summary_df.loc[[0], best_cols + extra_cols].T

                                 0
overall_wmape             4.889144
overall_mape              5.703177
context_length          168.000000
hidden_size              64.000000
dropout_rate              0.100000
learning_rate             0.001000
epochs                   10.000000
num_batches_per_epoch    30.000000
batch_size               32.000000
num_parallel_samples     50.000000
cluster_7_mape            5.703177
cluster_7_wmape           4.889144
cluster_7_epsilon_mape   55.669890

In [22]:
best_pred_path = best_row["prediction_path"]
best_pred_df = pd.read_parquet(best_pred_path)
best_pred_df.head()

,timestamp,meter_id,cluster_id,y_true,y_pred,forecast_start,ape,epsilon_ape
0,2014-07-01 00:00:00,MT_002,7,106.685633,100.081825,2014-07-01,6.189969,6.132487
1,2014-07-01 01:00:00,MT_002,7,88.193457,88.362907,2014-07-01,0.192135,0.189981
2,2014-07-01 02:00:00,MT_002,7,84.637269,84.708855,2014-07-01,0.084580,0.083592
3,2014-07-01 03:00:00,MT_002,7,83.926031,81.498848,2014-07-01,2.892051,2.857997
4,2014-07-01 04:00:00,MT_002,7,89.615932,84.852402,2014-07-01,5.315495,5.256835

In [23]:
best_config = TrainConfig(
    train_path="train_hourly_preprocessed.parquet",
    test_path="test_hourly_preprocessed.parquet",
    cluster_path="clusters_3models.parquet",
    cluster_ids=CLUSTER_IDS,
    output_dir=OUTPUT_DIR,
    freq="h",
    prediction_length=24,
    context_length=int(best_row["context_length"]),
    epochs=int(best_row["epochs"]),
    learning_rate=float(best_row["learning_rate"]),
    batch_size=int(best_row["batch_size"]),
    num_batches_per_epoch=int(best_row["num_batches_per_epoch"]),
    num_layers=2,
    hidden_size=int(best_row["hidden_size"]),
    dropout_rate=float(best_row["dropout_rate"]),
    num_parallel_samples=int(best_row["num_parallel_samples"]),
    seed=42,
    use_hour_of_day=True,
    use_day_of_week=True,
    use_weekend=True,
    use_month=True,
    use_holiday=True,
    holiday_country=HOLIDAY_COUNTRY,
)

In [24]:
set_seed(best_config.seed)

train_panel, test_panel, labels = load_cluster_panels(best_config)

history_panel = pd.concat([train_panel, test_panel]).sort_index()

meta = build_metadata(history_panel, labels, best_config)

future_start = history_panel.index.max() + pd.Timedelta(hours=1)
future_end = (future_start.to_period("M") + 2).end_time.floor("h")
future_index = pd.date_range(future_start, future_end, freq="h")

print("history:", history_panel.index.min(), "->", history_panel.index.max(), history_panel.shape)
print("future :", future_index.min(), "->", future_index.max(), len(future_index))

dynamic_feat_df = build_dynamic_features(history_panel.index, future_index, best_config)

predictor = fit_predictor(history_panel, meta, dynamic_feat_df.loc[history_panel.index.union(future_index)], best_config)

print("final predictor trained")

INFO: GPU available: True (cuda), used: True
INFO:lightning.pytorch.utilities.rank_zero:GPU available: True (cuda), used: True
INFO: TPU available: False, using: 0 TPU cores
INFO:lightning.pytorch.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO: HPU available: False, using: 0 HPUs
INFO:lightning.pytorch.utilities.rank_zero:HPU available: False, using: 0 HPUs
/usr/local/lib/python3.12/dist-packages/lightning/pytorch/trainer/configuration_validator.py:70: You defined a `validation_step` but have no `val_dataloader`. Skipping val loop.
/usr/local/lib/python3.12/dist-packages/lightning/pytorch/callbacks/model_checkpoint.py:654: Checkpoint directory /content/drive/MyDrive/Electricity-Project/checkpoints exists and is not empty.
INFO: LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
INFO:lightning.pytorch.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

history: 2012-10-01 00:00:00 -> 2014-12-31 23:00:00 (19728, 18)
future : 2015-01-01 00:00:00 -> 2015-03-31 23:00:00 2160

INFO:
  | Name  | Type        | Params | Mode  | In sizes                                                      | Out sizes
-----------------------------------------------------------------------------------------------------------------------------
0 | model | DeepARModel | 62.9 K | train | [[1, 1], [1, 1], [1, 888, 6], [1, 888], [1, 888], [1, 24, 6]] | [1, 100, 24]
-----------------------------------------------------------------------------------------------------------------------------
62.9 K    Trainable params
0         Non-trainable params
62.9 K    Total params
0.252     Total estimated model params size (MB)
11        Modules in train mode
0         Modules in eval mode
INFO:lightning.pytorch.callbacks.model_summary:
  | Name  | Type        | Params | Mode  | In sizes                                                      | Out sizes
-----------------------------------------------------------------------------------------------------------------------------
0 | model | DeepARModel | 62.9 K | train | [[1, 1], [1, 1], [1, 888, 6], [1, 888], [1, 888], [1, 24, 6]] | [1, 100, 24]
-----------------------------------------------------------------------------------------------------------------------------
62.9 K    Trainable params
0         Non-trainable params
62.9 K    Total params
0.252     Total estimated model params size (MB)
11        Modules in train mode
0         Modules in eval mode

Training: |          | 0/? [00:00<?, ?it/s]

INFO: Epoch 0, global step 30: 'train_loss' reached 7.19417 (best 7.19417), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=0-step=30.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 0, global step 30: 'train_loss' reached 7.19417 (best 7.19417), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=0-step=30.ckpt' as top 1
INFO: Epoch 1, global step 60: 'train_loss' reached 6.24994 (best 6.24994), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=1-step=60.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 1, global step 60: 'train_loss' reached 6.24994 (best 6.24994), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=1-step=60.ckpt' as top 1
INFO: Epoch 2, global step 90: 'train_loss' reached 5.99041 (best 5.99041), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=2-step=90.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 2, global step 90: 'train_loss' reached 5.99041 (best 5.99041), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=2-step=90.ckpt' as top 1
INFO: Epoch 3, global step 120: 'train_loss' reached 5.97269 (best 5.97269), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=3-step=120-v1.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 3, global step 120: 'train_loss' reached 5.97269 (best 5.97269), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=3-step=120-v1.ckpt' as top 1
INFO: Epoch 4, global step 150: 'train_loss' reached 5.79742 (best 5.79742), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=4-step=150.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 4, global step 150: 'train_loss' reached 5.79742 (best 5.79742), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=4-step=150.ckpt' as top 1
INFO: Epoch 5, global step 180: 'train_loss' reached 5.78039 (best 5.78039), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=5-step=180.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 5, global step 180: 'train_loss' reached 5.78039 (best 5.78039), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=5-step=180.ckpt' as top 1
INFO: Epoch 6, global step 210: 'train_loss' reached 5.57354 (best 5.57354), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=6-step=210.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 6, global step 210: 'train_loss' reached 5.57354 (best 5.57354), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=6-step=210.ckpt' as top 1
INFO: Epoch 7, global step 240: 'train_loss' was not in top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 7, global step 240: 'train_loss' was not in top 1
INFO: Epoch 8, global step 270: 'train_loss' was not in top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 8, global step 270: 'train_loss' was not in top 1
INFO: Epoch 9, global step 300: 'train_loss' reached 5.52636 (best 5.52636), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=9-step=300-v1.ckpt' as top 1
INFO:lightning.pytorch.utilities.rank_zero:Epoch 9, global step 300: 'train_loss' reached 5.52636 (best 5.52636), saving model to '/content/drive/MyDrive/Electricity-Project/checkpoints/epoch=9-step=300-v1.ckpt' as top 1
INFO: `Trainer.fit` stopped: `max_epochs=10` reached.
INFO:lightning.pytorch.utilities.rank_zero:`Trainer.fit` stopped: `max_epochs=10` reached.

final predictor trained

In [27]:
future_pred_frames = []
step = best_config.prediction_length  # 24

total_windows = sum((len(future_index) + step - 1) // step for _ in history_panel.columns)
progress = tqdm(total=total_windows, desc="Future rolling forecast", unit="window")

for meter_id in history_panel.columns:
    history = history_panel[meter_id].astype(float).copy()

    static_cat = [int(meta.loc[meter_id, "cluster_code"])]
    static_real = [float(meta.loc[meter_id, "log_mean_hourly_load"])]
    cluster_id = int(meta.loc[meter_id, "cluster_id"])

    meter_future_frames = []

    for start_idx in range(0, len(future_index), step):
        end_idx = min(start_idx + step, len(future_index))
        horizon = end_idx - start_idx
        forecast_slice = future_index[start_idx:end_idx]

        record = {
            "item_id": str(meter_id),
            "start": history.index[0],
            "target": history.to_numpy(),
            "feat_static_cat": static_cat,
            "feat_static_real": static_real,
        }

        if not dynamic_feat_df.empty:
            dynamic_index = history.index.append(forecast_slice)
            record["feat_dynamic_real"] = dynamic_feat_df.loc[dynamic_index].to_numpy(dtype=float).T

        ds = ListDataset([record], freq=best_config.freq)
        forecast = next(predictor.predict(ds, num_samples=best_config.num_parallel_samples))

        pred_mean = np.asarray(forecast.mean[:horizon], dtype=float)

        meter_future_frames.append(
            pd.DataFrame(
                {
                    "timestamp": forecast_slice,
                    "meter_id": meter_id,
                    "cluster_id": cluster_id,
                    "y_pred": pred_mean,
                }
            )
        )

        history_extension = pd.Series(pred_mean, index=forecast_slice)
        history = pd.concat([history, history_extension])

        progress.update(1)

    future_pred_frames.append(pd.concat(meter_future_frames, ignore_index=True))

progress.close()

future_pred_df = pd.concat(future_pred_frames, ignore_index=True)
future_pred_df.head()

Future rolling forecast:   0%|          | 0/1620 [00:00<?, ?window/s]

            timestamp meter_id  cluster_id     y_pred
0 2015-01-01 00:00:00   MT_002           7  80.311684
1 2015-01-01 01:00:00   MT_002           7  76.433128
2 2015-01-01 02:00:00   MT_002           7  75.637680
3 2015-01-01 03:00:00   MT_002           7  72.254333
4 2015-01-01 04:00:00   MT_002           7  73.069855

In [28]:
cluster_future_df = (
    future_pred_df.groupby(["timestamp", "cluster_id"], as_index=False)["y_pred"]
    .sum()
    .sort_values(["cluster_id", "timestamp"])
)

cluster_future_df.head()

            timestamp  cluster_id        y_pred
0 2015-01-01 00:00:00           7  40978.793724
1 2015-01-01 01:00:00           7  41221.941338
2 2015-01-01 02:00:00           7  40732.187233
3 2015-01-01 03:00:00           7  39581.415077
4 2015-01-01 04:00:00           7  38815.508118

In [29]:
future_pred_path = "outputs/future_3months_predictions_7.parquet"
cluster_future_path = "outputs/future_3months_cluster_sum_7.parquet"

future_pred_df.to_parquet(future_pred_path, index=False)
cluster_future_df.to_parquet(cluster_future_path, index=False)

print("saved meter-level forecast to:", future_pred_path)
print("saved cluster-level forecast to:", cluster_future_path)

saved meter-level forecast to: outputs/future_3months_predictions_7.parquet
saved cluster-level forecast to: outputs/future_3months_cluster_sum_7.parquet